#!/usr/bin/env python3

"""
Phase 135 Production Readiness Grader.

Consumes only evidence generated by earlier Phase 135 stages:

- repository discovery
- layer mapping
- dependency mapping
- import graph normalization
- runtime graph discovery
- contract discovery
- fintech capability grading
- AI capability grading

This grader does not:

- rescan the repository
- execute application code
- modify application code
- alter fintech or AI capability scores
- assign production-blocker severity
- approve deployment or live trading

Production readiness is graded independently across:

1. Architecture Integrity
2. Dependency Health
3. Runtime Readiness
4. Contract Readiness
5. Testing Readiness
6. Security and Identity
7. Operational Resilience
8. Persistence and Data Integrity
9. Observability and Auditability
10. Deployment Configuration
11. Fintech Production Readiness
12. AI Production Readiness
"""

from __future__ import annotations

from typing import Any, Callable


CheckEvaluator = Callable[[], tuple[bool, Any, str]]


class ProductionReadinessGrader:
    """
    Grade production readiness from existing Phase 135 evidence.
    """

    def __init__(
        self,
        discovery: dict[str, Any],
        layer_mapping: dict[str, Any],
        dependency_mapping: dict[str, Any],
        import_graph: dict[str, Any],
        runtime_graph: dict[str, Any],
        contract_discovery: dict[str, Any],
        fintech_capability: dict[str, Any],
        ai_capability: dict[str, Any],
    ) -> None:
        self.discovery = discovery
        self.layer_mapping = layer_mapping
        self.dependency_mapping = dependency_mapping
        self.import_graph = import_graph
        self.runtime_graph = runtime_graph
        self.contract_discovery = contract_discovery
        self.fintech_capability = fintech_capability
        self.ai_capability = ai_capability

        self.fintech_categories = {
            item["category_id"]: item
            for item in fintech_capability.get("categories", [])
        }

        self.ai_categories = {
            item["category_id"]: item
            for item in ai_capability.get("categories", [])
        }

        self.fintech_checks = self._build_check_index(
            fintech_capability
        )

        self.ai_checks = self._build_check_index(
            ai_capability
        )

        self.metrics = self._build_metrics()

    def grade(self) -> dict[str, Any]:
        categories = [
            self._grade_architecture_integrity(),
            self._grade_dependency_health(),
            self._grade_runtime_readiness(),
            self._grade_contract_readiness(),
            self._grade_testing_readiness(),
            self._grade_security_identity(),
            self._grade_operational_resilience(),
            self._grade_persistence_integrity(),
            self._grade_observability_auditability(),
            self._grade_deployment_configuration(),
            self._grade_fintech_readiness(),
            self._grade_ai_readiness(),
        ]

        total_score = round(
            sum(category["score"] for category in categories),
            2,
        )

        total_maximum = sum(
            category["maximum"] for category in categories
        )

        percentage = round(
            (
                total_score
                / total_maximum
                * 100
            )
            if total_maximum
            else 0.0,
            2,
        )

        readiness_status = self._readiness_status(percentage)

        failed_checks = []

        for category in categories:
            for check in category["checks"]:
                if check["passed"]:
                    continue

                failed_checks.append(
                    {
                        "category_id": category["category_id"],
                        "category": category["category"],
                        "check_id": check["check_id"],
                        "check": check["check"],
                        "observed": check["observed"],
                        "requirement": check["requirement"],
                        "points_available": check["maximum"],
                    }
                )

        strongest = sorted(
            categories,
            key=lambda item: (
                -item["percentage"],
                item["category"],
            ),
        )[:5]

        weakest = sorted(
            categories,
            key=lambda item: (
                item["percentage"],
                item["category"],
            ),
        )[:5]

        return {
            "grading_mode": "evidence_based_static_readiness",
            "application_executed": False,
            "repository_rescanned": False,
            "architecture_assumed": False,
            "fintech_score_modified": False,
            "ai_score_modified": False,
            "production_blockers_assessed": False,
            "deployment_approved": False,
            "live_trading_approved": False,
            "summary": {
                "category_count": len(categories),
                "total_score": total_score,
                "total_maximum": total_maximum,
                "percentage": percentage,
                "status": readiness_status,
                "checks_total": sum(
                    len(category["checks"])
                    for category in categories
                ),
                "checks_passed": sum(
                    category["checks_passed"]
                    for category in categories
                ),
                "checks_failed": sum(
                    category["checks_failed"]
                    for category in categories
                ),
                "readiness_gaps": len(failed_checks),
            },
            "categories": categories,
            "strongest_categories": [
                self._category_summary(item)
                for item in strongest
            ],
            "weakest_categories": [
                self._category_summary(item)
                for item in weakest
            ],
            "readiness_gaps": sorted(
                failed_checks,
                key=lambda item: (
                    item["category"],
                    item["check"],
                ),
            ),
            "metric_snapshot": dict(
                sorted(self.metrics.items())
            ),
            "scoring_contract": {
                "category_maximum": 100,
                "check_maximum": 20,
                "category_count": 12,
                "readiness_status_thresholds": {
                    "Not Ready": "0-39.99",
                    "Early": "40-59.99",
                    "Conditional": "60-79.99",
                    "Production Candidate": "80-89.99",
                    "Production Ready": "90-100",
                },
                "overall_score_is": (
                    "static production readiness evidence"
                ),
                "overall_score_is_not": [
                    "deployment approval",
                    "live trading approval",
                    "regulatory compliance certification",
                    "security certification",
                    "runtime correctness proof",
                    "production blocker assessment",
                ],
            },
            "limitations": [
                (
                    "Production readiness is inferred from static repository "
                    "evidence and previously generated capability grades."
                ),
                (
                    "No application process, database, broker, model provider, "
                    "network service, or frontend was executed."
                ),
                (
                    "Passing a readiness check does not prove runtime correctness, "
                    "security, reliability, or regulatory compliance."
                ),
                (
                    "Production blocker severity is intentionally deferred to "
                    "Stage 10."
                ),
            ],
        }

    def _grade_architecture_integrity(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="architecture_integrity",
            category="Architecture Integrity",
            checks=[
                self._maximum_check(
                    "ambiguous_regions",
                    "Limited ambiguous source ownership",
                    self.metrics["ambiguous_regions"],
                    10,
                ),
                self._maximum_check(
                    "multi_package_cycles",
                    "No cross-package dependency cycles",
                    self.metrics["multi_package_cycles"],
                    0,
                ),
                self._maximum_check(
                    "dependency_cycles",
                    "No file-level dependency cycles",
                    self.metrics["dependency_cycles"],
                    0,
                ),
                self._minimum_check(
                    "active_source_ownership",
                    "Active source ownership ratio",
                    self.metrics["active_source_ratio"],
                    0.80,
                ),
                self._maximum_check(
                    "duplicate_contract_names",
                    "No duplicate contract names",
                    self.metrics["duplicate_contract_names"],
                    0,
                ),
            ],
        )

    def _grade_dependency_health(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="dependency_health",
            category="Dependency Health",
            checks=[
                self._maximum_check(
                    "unresolved_dependencies",
                    "Controlled unresolved dependencies",
                    self.metrics["unresolved_dependencies"],
                    20,
                ),
                self._maximum_check(
                    "dependency_parse_errors",
                    "No dependency parse errors",
                    self.metrics["dependency_parse_errors"],
                    0,
                ),
                self._minimum_check(
                    "active_dependency_ratio",
                    "Active dependency-edge ratio",
                    self.metrics["active_dependency_ratio"],
                    0.90,
                ),
                self._minimum_check(
                    "internal_dependency_edges",
                    "Internal dependency graph discovered",
                    self.metrics["internal_dependency_edges"],
                    1,
                ),
                self._minimum_check(
                    "package_nodes",
                    "Package graph discovered",
                    self.metrics["package_nodes"],
                    1,
                ),
            ],
        )

    def _grade_runtime_readiness(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="runtime_readiness",
            category="Runtime Readiness",
            checks=[
                self._minimum_check(
                    "active_entrypoints",
                    "Active application entrypoints",
                    self.metrics["active_entrypoints"],
                    1,
                ),
                self._minimum_check(
                    "runtime_routes",
                    "Runtime routes discovered",
                    self.metrics["runtime_routes"],
                    1,
                ),
                self._minimum_check(
                    "runtime_reachability",
                    "Active runtime reachability ratio",
                    self.metrics["runtime_reachability_ratio"],
                    0.50,
                ),
                self._maximum_check(
                    "runtime_parse_errors",
                    "No runtime parse errors",
                    self.metrics["runtime_parse_errors"],
                    0,
                ),
                self._maximum_check(
                    "runtime_cycles",
                    "No runtime dependency cycles",
                    self.metrics["runtime_cycles"],
                    0,
                ),
            ],
        )

    def _grade_contract_readiness(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="contract_readiness",
            category="Contract Readiness",
            checks=[
                self._minimum_check(
                    "active_contracts",
                    "Active contracts discovered",
                    self.metrics["active_contracts"],
                    20,
                ),
                self._minimum_check(
                    "route_contract_coverage",
                    "Explicit route contract coverage",
                    self.metrics["route_contract_coverage"],
                    80.0,
                ),
                self._minimum_check(
                    "routes_with_response_models",
                    "Explicit response models",
                    self.metrics["routes_with_response_models"],
                    1,
                ),
                self._maximum_check(
                    "duplicate_contract_names",
                    "No duplicate contract declarations",
                    self.metrics["duplicate_contract_names"],
                    0,
                ),
                self._maximum_check(
                    "contract_parse_errors",
                    "No contract parse errors",
                    self.metrics["contract_parse_errors"],
                    0,
                ),
            ],
        )

    def _grade_testing_readiness(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="testing_readiness",
            category="Testing Readiness",
            checks=[
                self._minimum_check(
                    "test_files",
                    "Repository test-file inventory",
                    self.metrics["test_files"],
                    50,
                ),
                self._minimum_check(
                    "test_to_source_ratio",
                    "Test-to-source ratio",
                    self.metrics["test_to_source_ratio"],
                    0.10,
                ),
                self._minimum_check(
                    "fintech_test_checks",
                    "Fintech test-capability checks",
                    self.metrics["fintech_test_checks_passed"],
                    8,
                ),
                self._minimum_check(
                    "ai_test_checks",
                    "AI test-capability checks",
                    self.metrics["ai_test_checks_passed"],
                    8,
                ),
                self._minimum_check(
                    "route_contract_coverage",
                    "API contract coverage supports testing",
                    self.metrics["route_contract_coverage"],
                    80.0,
                ),
            ],
        )

    def _grade_security_identity(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="security_identity",
            category="Security and Identity",
            checks=[
                self._category_check(
                    "fintech_auth_score",
                    "Authentication and identity capability",
                    self.fintech_categories,
                    "authentication_identity",
                    80.0,
                ),
                self._category_check(
                    "ai_safety_score",
                    "AI safety and governance capability",
                    self.ai_categories,
                    "ai_safety_governance",
                    80.0,
                ),
                self._capability_check(
                    "credential_handling",
                    "Credential or token handling",
                    self.fintech_checks,
                    "credential_or_token_handling",
                ),
                self._capability_check(
                    "authentication_tests",
                    "Authentication tests",
                    self.fintech_checks,
                    "auth_tests",
                ),
                self._capability_check(
                    "input_validation",
                    "Prompt or input validation",
                    self.ai_checks,
                    "prompt_injection_or_input_validation",
                ),
            ],
        )

    def _grade_operational_resilience(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="operational_resilience",
            category="Operational Resilience",
            checks=[
                self._capability_check(
                    "provider_failure_handling",
                    "AI provider failure handling",
                    self.ai_checks,
                    "provider_failure_handling",
                ),
                self._capability_check(
                    "local_model_health",
                    "Local model health monitoring",
                    self.ai_checks,
                    "local_model_health",
                ),
                self._minimum_check(
                    "runtime_signals",
                    "Operational runtime signals",
                    self.metrics["runtime_signals"],
                    10,
                ),
                self._maximum_check(
                    "runtime_parse_errors",
                    "No runtime parse failures",
                    self.metrics["runtime_parse_errors"],
                    0,
                ),
                self._maximum_check(
                    "dependency_cycles",
                    "No dependency cycles affecting resilience",
                    self.metrics["dependency_cycles"],
                    0,
                ),
            ],
        )

    def _grade_persistence_integrity(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="persistence_integrity",
            category="Persistence and Data Integrity",
            checks=[
                self._category_check(
                    "database_score",
                    "Database and persistence capability",
                    self.fintech_categories,
                    "database_persistence",
                    80.0,
                ),
                self._category_check(
                    "audit_score",
                    "Audit and journal capability",
                    self.fintech_categories,
                    "audit_logging",
                    80.0,
                ),
                self._capability_check(
                    "conversation_persistence",
                    "Persistent conversation models",
                    self.ai_checks,
                    "conversation_persistence",
                ),
                self._capability_check(
                    "immutable_audit",
                    "Append-only or immutable audit evidence",
                    self.fintech_checks,
                    "immutable_or_append_only",
                ),
                self._capability_check(
                    "repository_store",
                    "Repository or store abstraction",
                    self.fintech_checks,
                    "repository_or_store",
                ),
            ],
        )

    def _grade_observability_auditability(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="observability_auditability",
            category="Observability and Auditability",
            checks=[
                self._category_check(
                    "ai_observability_score",
                    "AI observability capability",
                    self.ai_categories,
                    "ai_observability_testing",
                    80.0,
                ),
                self._category_check(
                    "audit_logging_score",
                    "Audit and logging capability",
                    self.fintech_categories,
                    "audit_logging",
                    80.0,
                ),
                self._capability_check(
                    "ai_logging",
                    "AI-specific logging",
                    self.ai_checks,
                    "ai_logging",
                ),
                self._capability_check(
                    "ai_trace",
                    "AI runtime trace",
                    self.ai_checks,
                    "ai_trace",
                ),
                self._capability_check(
                    "runtime_logging",
                    "Runtime logging or tracing",
                    self.fintech_checks,
                    "runtime_logging",
                ),
            ],
        )

    def _grade_deployment_configuration(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="deployment_configuration",
            category="Deployment Configuration",
            checks=[
                self._minimum_check(
                    "configuration_files",
                    "Configuration-file inventory",
                    self.metrics["configuration_files"],
                    5,
                ),
                self._boolean_check(
                    "docker_compose",
                    "Docker Compose evidence",
                    self.metrics["docker_compose_present"],
                ),
                self._minimum_check(
                    "environment_access",
                    "Runtime environment configuration",
                    self.metrics["environment_access_signals"],
                    1,
                ),
                self._minimum_check(
                    "active_entrypoints",
                    "Deployable application entrypoint",
                    self.metrics["active_entrypoints"],
                    1,
                ),
                self._minimum_check(
                    "runtime_routes",
                    "Exposed application routes",
                    self.metrics["runtime_routes"],
                    1,
                ),
            ],
        )

    def _grade_fintech_readiness(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="fintech_production_readiness",
            category="Fintech Production Readiness",
            checks=[
                self._minimum_check(
                    "fintech_capability",
                    "Overall fintech capability",
                    self.metrics["fintech_percentage"],
                    80.0,
                ),
                self._category_check(
                    "broker_score",
                    "Broker integration capability",
                    self.fintech_categories,
                    "broker_integration",
                    80.0,
                ),
                self._category_check(
                    "risk_score",
                    "Risk-engine capability",
                    self.fintech_categories,
                    "risk_engine",
                    80.0,
                ),
                self._category_check(
                    "auth_score",
                    "Authentication capability",
                    self.fintech_categories,
                    "authentication_identity",
                    80.0,
                ),
                self._maximum_check(
                    "fintech_gaps",
                    "Controlled fintech capability gaps",
                    self.metrics["fintech_gaps"],
                    5,
                ),
            ],
        )

    def _grade_ai_readiness(self) -> dict[str, Any]:
        return self._grade_category(
            category_id="ai_production_readiness",
            category="AI Production Readiness",
            checks=[
                self._minimum_check(
                    "ai_capability",
                    "Overall AI capability",
                    self.metrics["ai_percentage"],
                    80.0,
                ),
                self._category_check(
                    "tool_score",
                    "Tool invocation capability",
                    self.ai_categories,
                    "tool_invocation",
                    80.0,
                ),
                self._category_check(
                    "ai_safety_score",
                    "AI safety capability",
                    self.ai_categories,
                    "ai_safety_governance",
                    80.0,
                ),
                self._category_check(
                    "explainability_score",
                    "Confidence and explainability",
                    self.ai_categories,
                    "confidence_explainability",
                    80.0,
                ),
                self._maximum_check(
                    "ai_gaps",
                    "Controlled AI capability gaps",
                    self.metrics["ai_gaps"],
                    5,
                ),
            ],
        )

    def _grade_category(
        self,
        category_id: str,
        category: str,
        checks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        score = round(
            sum(check["score"] for check in checks),
            2,
        )

        maximum = round(
            sum(check["maximum"] for check in checks),
            2,
        )

        percentage = round(
            (
                score
                / maximum
                * 100
            )
            if maximum
            else 0.0,
            2,
        )

        return {
            "category_id": category_id,
            "category": category,
            "score": score,
            "maximum": maximum,
            "percentage": percentage,
            "status": self._category_status(percentage),
            "checks_passed": sum(
                1
                for check in checks
                if check["passed"]
            ),
            "checks_failed": sum(
                1
                for check in checks
                if not check["passed"]
            ),
            "checks": checks,
            "evidence": [
                check["evidence"]
                for check in checks
            ],
            "missing": [
                check["requirement"]
                for check in checks
                if not check["passed"]
            ],
            "notes": [
                (
                    "Readiness evidence is static and does not constitute "
                    "deployment approval."
                )
            ],
        }

    def _minimum_check(
        self,
        check_id: str,
        label: str,
        observed: float,
        minimum: float,
    ) -> dict[str, Any]:
        passed = observed >= minimum

        return self._check_result(
            check_id=check_id,
            label=label,
            passed=passed,
            observed=observed,
            requirement=f"Observed value must be >= {minimum}.",
            evidence={
                "comparison": "minimum",
                "observed": observed,
                "required": minimum,
            },
        )

    def _maximum_check(
        self,
        check_id: str,
        label: str,
        observed: float,
        maximum: float,
    ) -> dict[str, Any]:
        passed = observed <= maximum

        return self._check_result(
            check_id=check_id,
            label=label,
            passed=passed,
            observed=observed,
            requirement=f"Observed value must be <= {maximum}.",
            evidence={
                "comparison": "maximum",
                "observed": observed,
                "required": maximum,
            },
        )

    def _boolean_check(
        self,
        check_id: str,
        label: str,
        observed: bool,
    ) -> dict[str, Any]:
        return self._check_result(
            check_id=check_id,
            label=label,
            passed=bool(observed),
            observed=bool(observed),
            requirement="Required evidence must be present.",
            evidence={
                "comparison": "boolean",
                "observed": bool(observed),
                "required": True,
            },
        )

    def _category_check(
        self,
        check_id: str,
        label: str,
        categories: dict[str, dict[str, Any]],
        category_id: str,
        minimum: float,
    ) -> dict[str, Any]:
        category = categories.get(category_id, {})
        observed = float(category.get("percentage", 0.0))

        return self._minimum_check(
            check_id=check_id,
            label=label,
            observed=observed,
            minimum=minimum,
        )

    def _capability_check(
        self,
        check_id: str,
        label: str,
        checks: dict[str, dict[str, Any]],
        capability_check_id: str,
    ) -> dict[str, Any]:
        capability = checks.get(
            capability_check_id,
            {},
        )

        passed = bool(
            capability.get("passed", False)
        )

        return self._check_result(
            check_id=check_id,
            label=label,
            passed=passed,
            observed=passed,
            requirement=(
                f"Capability check {capability_check_id!r} must pass."
            ),
            evidence={
                "capability_check_id": capability_check_id,
                "capability_check": capability,
            },
        )

    @staticmethod
    def _check_result(
        check_id: str,
        label: str,
        passed: bool,
        observed: Any,
        requirement: str,
        evidence: Any,
    ) -> dict[str, Any]:
        return {
            "check_id": check_id,
            "check": label,
            "score": 20.0 if passed else 0.0,
            "maximum": 20.0,
            "passed": passed,
            "observed": observed,
            "requirement": (
                None
                if passed
                else requirement
            ),
            "evidence": evidence,
        }

    def _build_metrics(self) -> dict[str, Any]:
        discovery_summary = self.discovery.get(
            "summary",
            {},
        )

        layer_summary = self.layer_mapping.get(
            "summary",
            {},
        )

        ownership = (
            self.layer_mapping
            .get("ownership_summary", {})
            .get("source_ownership_estimate", {})
        )

        dependency_summary = self.dependency_mapping.get(
            "summary",
            {},
        )

        import_summary = self.import_graph.get(
            "summary",
            {},
        )

        runtime_summary = self.runtime_graph.get(
            "summary",
            {},
        )

        contract_summary = self.contract_discovery.get(
            "summary",
            {},
        )

        route_coverage = self.contract_discovery.get(
            "route_contract_coverage",
            {},
        )

        total_sources = float(
            discovery_summary.get("source_files", 0)
        )

        active_sources = float(
            ownership.get("active_source_files", 0)
        )

        active_edges = float(
            dependency_summary.get("active_internal_edges", 0)
        )

        all_edges = float(
            dependency_summary.get(
                "internal_dependency_edges",
                0,
            )
        )

        reachable_files = float(
            runtime_summary.get("reachable_files", 0)
        )

        active_runtime_files = (
            reachable_files
            + float(
                runtime_summary.get(
                    "unreachable_active_files",
                    0,
                )
            )
        )

        test_files = float(
            discovery_summary.get("test_files", 0)
        )

        multi_package_cycles = sum(
            1
            for cycle in (
                self.import_graph
                .get("package_graph", {})
                .get("cycles", [])
            )
            if int(cycle.get("node_count", 0)) > 1
        )

        environment_access_signals = int(
            self.runtime_graph
            .get("signal_counts", {})
            .get("environment_access", 0)
        )

        framework_names = {
            signal.get("framework_or_system")
            for signal in self.layer_mapping.get(
                "framework_signals",
                [],
            )
        }

        return {
            "total_source_files": total_sources,
            "active_source_files": active_sources,
            "active_source_ratio": self._safe_ratio(
                active_sources,
                total_sources,
            ),
            "ambiguous_regions": float(
                layer_summary.get("ambiguous_regions", 0)
            ),
            "dependency_cycles": float(
                dependency_summary.get(
                    "dependency_cycles",
                    0,
                )
            ),
            "multi_package_cycles": float(
                multi_package_cycles
            ),
            "duplicate_contract_names": float(
                contract_summary.get(
                    "duplicate_contract_names",
                    0,
                )
            ),
            "unresolved_dependencies": float(
                dependency_summary.get(
                    "unresolved_dependencies",
                    0,
                )
            ),
            "dependency_parse_errors": float(
                dependency_summary.get(
                    "files_with_parse_errors",
                    0,
                )
            ),
            "active_dependency_ratio": self._safe_ratio(
                active_edges,
                all_edges,
            ),
            "internal_dependency_edges": all_edges,
            "package_nodes": float(
                import_summary.get("package_nodes", 0)
            ),
            "active_entrypoints": float(
                runtime_summary.get("active_entrypoints", 0)
            ),
            "runtime_routes": float(
                runtime_summary.get("routes", 0)
            ),
            "runtime_reachability_ratio": self._safe_ratio(
                reachable_files,
                active_runtime_files,
            ),
            "runtime_parse_errors": float(
                runtime_summary.get("parse_errors", 0)
            ),
            "runtime_cycles": float(
                runtime_summary.get("runtime_cycles", 0)
            ),
            "runtime_signals": float(
                runtime_summary.get("runtime_signals", 0)
            ),
            "active_contracts": float(
                contract_summary.get("active_contracts", 0)
            ),
            "route_contract_coverage": float(
                route_coverage.get(
                    "explicit_contract_coverage_percent",
                    0.0,
                )
            ),
            "routes_with_response_models": float(
                route_coverage.get(
                    "routes_with_response_models",
                    0,
                )
            ),
            "contract_parse_errors": float(
                contract_summary.get("parse_errors", 0)
            ),
            "test_files": test_files,
            "test_to_source_ratio": self._safe_ratio(
                test_files,
                total_sources,
            ),
            "fintech_test_checks_passed": float(
                self._count_test_checks(
                    self.fintech_capability
                )
            ),
            "ai_test_checks_passed": float(
                self._count_test_checks(
                    self.ai_capability
                )
            ),
            "configuration_files": float(
                discovery_summary.get(
                    "config_files",
                    0,
                )
            ),
            "docker_compose_present": (
                "Docker_Compose" in framework_names
            ),
            "environment_access_signals": float(
                environment_access_signals
            ),
            "fintech_percentage": float(
                self.fintech_capability
                .get("summary", {})
                .get("percentage", 0.0)
            ),
            "fintech_gaps": float(
                self.fintech_capability
                .get("summary", {})
                .get("capability_gaps", 0)
            ),
            "ai_percentage": float(
                self.ai_capability
                .get("summary", {})
                .get("percentage", 0.0)
            ),
            "ai_gaps": float(
                self.ai_capability
                .get("summary", {})
                .get("capability_gaps", 0)
            ),
        }

    @staticmethod
    def _build_check_index(
        capability: dict[str, Any],
    ) -> dict[str, dict[str, Any]]:
        index = {}

        for category in capability.get(
            "categories",
            [],
        ):
            for check in category.get("checks", []):
                check_id = check.get("check_id")

                if check_id:
                    index[check_id] = check

        return index

    @staticmethod
    def _count_test_checks(
        capability: dict[str, Any],
    ) -> int:
        count = 0

        for category in capability.get(
            "categories",
            [],
        ):
            for check in category.get("checks", []):
                check_id = str(
                    check.get("check_id", "")
                )

                label = str(
                    check.get("check", "")
                ).lower()

                if (
                    "test" in check_id.lower()
                    or "test" in label
                ):
                    if check.get("passed"):
                        count += 1

        return count

    @staticmethod
    def _safe_ratio(
        numerator: float,
        denominator: float,
    ) -> float:
        if denominator <= 0:
            return 0.0

        return round(
            numerator / denominator,
            6,
        )

    @staticmethod
    def _category_summary(
        category: dict[str, Any],
    ) -> dict[str, Any]:
        return {
            "category_id": category["category_id"],
            "category": category["category"],
            "score": category["score"],
            "maximum": category["maximum"],
            "percentage": category["percentage"],
            "status": category["status"],
        }

    @staticmethod
    def _category_status(
        percentage: float,
    ) -> str:
        if percentage < 40:
            return "Not Ready"

        if percentage < 60:
            return "Early"

        if percentage < 80:
            return "Conditional"

        if percentage < 90:
            return "Candidate"

        return "Ready"

    @staticmethod
    def _readiness_status(
        percentage: float,
    ) -> str:
        if percentage < 40:
            return "Not Ready"

        if percentage < 60:
            return "Early"

        if percentage < 80:
            return "Conditional"

        if percentage < 90:
            return "Production Candidate"

        return "Production Ready"
