"""Candidate quarantine / trash path.

Generated by 81A_CANDIDATE_QUARANTINE_TRASH_PATH.

This is contract-only.
No deletion, no mutation, no training, no strategy DB writes,
no promotion, no broker execution, no live trading.
"""

from __future__ import annotations


QUARANTINE_PATH_ENABLED = False
TRASH_PATH_ENABLED = False
DELETE_ALLOWED = False
MUTATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

QUARANTINE_ROOT = "runtime/replay_runtime_architecture/candidate_quarantine/"
TRASH_ROOT = "runtime/replay_runtime_architecture/candidate_trash/"


def quarantine_trash_status() -> dict:
    return {
        "quarantine_path_enabled": QUARANTINE_PATH_ENABLED,
        "trash_path_enabled": TRASH_PATH_ENABLED,
        "delete_allowed": DELETE_ALLOWED,
        "mutation_allowed": MUTATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "quarantine_root": QUARANTINE_ROOT,
        "trash_root": TRASH_ROOT,
    }


def preview_quarantine_record(candidate_id: str, reason: str) -> dict:
    return {
        "mode": "PREVIEW_ONLY",
        "candidate_id": candidate_id,
        "reason": reason,
        "quarantine_allowed_now": QUARANTINE_PATH_ENABLED,
        "trash_allowed_now": TRASH_PATH_ENABLED,
        "delete_allowed_now": DELETE_ALLOWED,
        "status": quarantine_trash_status(),
    }
