"""Dev Territory Command Registry.

Generated by 106B_DEV_TERRITORY_COMMAND_REGISTRY_STUB.

This registry is sandbox-facing only.
It grants analytical capability only.
It never grants persistence, mutation, promotion, broker execution, or live trading.
"""

from __future__ import annotations

DEV_TERRITORY_REGISTRY_ENABLED = True
REGISTRY_WRITE_TO_RUNTIME_ENABLED = False
TRAINING_EXECUTION_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

COMMANDS = [
    {
        "level": 1,
        "name": "SCOUT",
        "command": "Neuro, expand your territory. Scout the approved landscape.",
        "purpose": "Read-only exploration of certified data.",
        "allowed": [
            "read certified historical data",
            "read approved research",
            "produce observations"
        ],
        "forbidden": [
            "strategy DB writes",
            "mutation",
            "promotion",
            "broker execution",
            "live execution"
        ]
    },
    {
        "level": 2,
        "name": "HUNTING_PARTY",
        "command": "Neuro, send out a hunting party. Bring back five promising opportunities.",
        "purpose": "Generate sandbox candidate ideas only.",
        "allowed": [
            "generate candidate ideas",
            "score hypotheses",
            "write sandbox-only artifacts"
        ],
        "forbidden": [
            "strategy DB writes",
            "promotion",
            "broker execution",
            "live execution"
        ]
    },
    {
        "level": 3,
        "name": "EXPLORE_NEW_LANDS",
        "command": "Neuro, explore beyond our territory. Find new hunting grounds.",
        "purpose": "Massive sandbox exploration after approval.",
        "allowed": [
            "large-scale exploration",
            "compare territories",
            "request expansion"
        ],
        "forbidden": [
            "unapproved expansion",
            "strategy DB writes",
            "broker execution",
            "live execution"
        ]
    },
    {
        "level": 4,
        "name": "ALPHA_TRIALS",
        "command": "Neuro, begin the Alpha Trials. Only the strongest survive.",
        "purpose": "Rank sandbox candidates through replay/stress scoring.",
        "allowed": [
            "rank candidates",
            "eliminate weak sandbox ideas",
            "produce survivor report"
        ],
        "forbidden": [
            "delete production strategies",
            "promote candidates",
            "broker execution"
        ]
    },
    {
        "level": 5,
        "name": "WOLF_MASTER_REPORT",
        "command": "Neuro, return to the den. Report to your Wolf Master.",
        "purpose": "Full human review report.",
        "allowed": [
            "summarize training",
            "summarize candidates",
            "recommend next action"
        ],
        "forbidden": [
            "approval without human",
            "DB writes",
            "promotion",
            "broker execution"
        ]
    },
    {
        "level": 6,
        "name": "EXPAND_THE_PACK",
        "command": "Neuro, expand the Pack. Move only approved survivors into Candidate Review.",
        "purpose": "Preview candidate review movement only.",
        "allowed": [
            "prepare candidate review package"
        ],
        "forbidden": [
            "strategy DB writes",
            "broker execution",
            "live execution"
        ]
    },
    {
        "level": 7,
        "name": "DEFEND_TERRITORY",
        "command": "Neuro, defend the Territory. Protect the pack using only certified knowledge.",
        "purpose": "Future production-only certified strategy mode.",
        "allowed": [
            "use certified knowledge only"
        ],
        "forbidden": [
            "exploration",
            "experimentation",
            "mutation",
            "uncertified strategy use"
        ]
    }
]

DOCTRINE = {
    "territory_maturity_rule": "Strengthen weakest known territory before requesting new expansion.",
    "expansion_request_phrase": "Wolf Master, we have expanded as much as we can in our current territory. Could we add more prey to search for?",
    "global_rule": "Territory commands grant analytical capability only. They never grant persistence, mutation, promotion, broker execution, or live trading.",
    "confidence_bands": {
        "95_100": "Alpha Territory",
        "90_94": "Stable Territory",
        "80_89": "Developing Territory",
        "70_79": "Weak Territory",
        "below_70": "Unstable Territory"
    }
}


def registry_status() -> dict:
    return {
        "dev_territory_registry_enabled": DEV_TERRITORY_REGISTRY_ENABLED,
        "registry_write_to_runtime_enabled": REGISTRY_WRITE_TO_RUNTIME_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "command_count": len(COMMANDS),
    }


def list_dev_territory_commands() -> list[dict]:
    return COMMANDS


def get_dev_territory_doctrine() -> dict:
    return DOCTRINE
