"""Dev command read-only executor.

Generated by 108B_DEV_COMMAND_READ_ONLY_EXECUTION_STUB.

Executor is read-only.
It may list command intent and doctrine only.
It cannot train, mutate, write DB records, promote candidates,
touch broker systems, or execute live trades.
"""

from __future__ import annotations

COMMAND_EXECUTION_ENABLED = True
READ_ONLY_PREVIEW_ENABLED = True
TRAINING_EXECUTION_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def executor_status() -> dict:
    return {
        "command_execution_enabled": COMMAND_EXECUTION_ENABLED,
        "read_only_preview_enabled": READ_ONLY_PREVIEW_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def preview_dev_command(command_name: str) -> dict:
    return {
        "mode": "READ_ONLY_COMMAND_PREVIEW",
        "command_name": command_name,
        "executed": False,
        "allowed_now": ["read command registry", "read doctrine", "produce preview response"],
        "blocked_now": [
            "training execution",
            "learner writes",
            "mutation",
            "queue writes",
            "strategy DB writes",
            "promotion",
            "broker execution",
            "live execution",
        ],
        "status": executor_status(),
    }
