"""Fixture replay calculator facade.

Generated by 70B_FIXTURE_REPLAY_CALCULATOR_SOURCE_CREATION.

This is a fixture-only calculator facade.
It may calculate fixture metrics, but it must not run strategy replay,
write strategy DB, promote candidates, place broker orders, or enable live trading.
"""

from __future__ import annotations

import csv
from pathlib import Path

from backend.app.stacks.strategy_candidate_sandbox.L2_domain.bar_replay_math_contract import (
    calculate_simple_returns,
    calculate_cumulative_return,
    calculate_rolling_mean,
    calculate_rolling_volatility,
    calculate_max_drawdown,
    calculate_trade_count_proxy,
    contract_status,
)


REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def facade_status() -> dict:
    return {
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "math_contract": contract_status(),
    }


def load_fixture_bars(csv_path: str | Path) -> list[dict]:
    path = Path(csv_path)

    with path.open("r", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    return rows


def extract_close_prices(rows: list[dict]) -> list[float]:
    return [float(row["close"]) for row in rows]


def build_equity_curve_from_returns(returns: list[float], starting_equity: float = 1.0) -> list[float]:
    equity = starting_equity
    curve = [equity]

    for value in returns:
        equity *= 1.0 + value
        curve.append(equity)

    return curve


def calculate_fixture_metrics(csv_path: str | Path) -> dict:
    rows = load_fixture_bars(csv_path)
    closes = extract_close_prices(rows)

    returns = calculate_simple_returns(closes)
    equity_curve = build_equity_curve_from_returns(returns)

    signal_states = [1 if idx > 0 else 0 for idx, _ in enumerate(closes)]

    return {
        "dataset_id": "fixture_ohlcv_v1",
        "row_count": len(rows),
        "simple_returns": returns,
        "cumulative_return": calculate_cumulative_return(returns),
        "rolling_mean_3": calculate_rolling_mean(closes, 3),
        "rolling_volatility_3": calculate_rolling_volatility(returns, 3),
        "max_drawdown": calculate_max_drawdown(equity_curve),
        "trade_count_proxy": calculate_trade_count_proxy(signal_states),
        "safety": facade_status(),
    }
