"""
Learning Artifact Pipeline

Generated by 123B_LEARNING_ARTIFACT_PIPELINE_STUB

Read-only pipeline:

Replay Row
    ↓
Feature Extraction
    ↓
Decision
    ↓
Reward
    ↓
Learning Artifact

NO DATABASE WRITES
NO STRATEGY PROMOTION
NO BROKER
NO LIVE EXECUTION
"""

from __future__ import annotations

from typing import Any

from backend.app.stacks.strategy_candidate_sandbox.learning_feature_extractor import (
    extract_learning_features,
)

from backend.app.stacks.strategy_candidate_sandbox.learning_reward_scorer import (
    score_decision_reward,
)

from backend.app.stacks.strategy_candidate_sandbox.learning_artifact_contract import (
    build_learning_artifact_contract,
)

PIPELINE_ENABLED=True

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False


def pipeline_status()->dict:

    return {

        "pipeline_enabled":PIPELINE_ENABLED,
        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }


def build_learning_artifact(

    *,
    run_id:str,
    symbol:str,
    row:dict[str,Any],
    previous_close:float|None,
    next_close:float|None,
    decision:str,
    cycle:int,

)->dict:

    features=extract_learning_features(
        row,
        previous_close,
    )

    reward=score_decision_reward(
        decision,
        row.get("close"),
        next_close,
    )

    artifact=build_learning_artifact_contract(

        run_id=run_id,
        symbol=symbol,
        date=str(row.get("date")),
        cycle=cycle,
        features=features,
        decision=decision,
        reward=reward["reward"],
        confidence=reward["confidence"],
        source={
            "reward":reward,
            "pipeline":"learning_artifact_pipeline",
        },
    )

    return artifact
