"""Long training run executor stub.

Generated by 120B_LONG_TRAINING_RUN_EXECUTOR_STUB.

Defines the 8-hour training executor contract only.
Does not run training yet.
Does not write DB records.
Does not promote strategies.
Does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, UTC
import json

LONG_TRAINING_EXECUTOR_ENABLED = True
TRAINING_EXECUTION_ENABLED = True
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

DEFAULT_DURATION_SECONDS = 28800
DEFAULT_HEARTBEAT_SECONDS = 30
DEFAULT_CHECKPOINT_SECONDS = 300


def executor_status() -> dict:
    return {
        "long_training_executor_enabled": LONG_TRAINING_EXECUTOR_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "default_duration_seconds": DEFAULT_DURATION_SECONDS,
        "default_heartbeat_seconds": DEFAULT_HEARTBEAT_SECONDS,
        "default_checkpoint_seconds": DEFAULT_CHECKPOINT_SECONDS,
    }


def build_long_training_plan(
    run_id: str,
    repository_manifest: str,
    duration_seconds: int = DEFAULT_DURATION_SECONDS,
) -> dict:
    return {
        "run_id": run_id,
        "repository_manifest": repository_manifest,
        "duration_seconds": duration_seconds,
        "heartbeat_seconds": DEFAULT_HEARTBEAT_SECONDS,
        "checkpoint_seconds": DEFAULT_CHECKPOINT_SECONDS,
        "resume_supported": True,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "created_at": datetime.now(UTC).isoformat(),
    }


def write_heartbeat(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "timestamp": datetime.now(UTC).isoformat(),
        "payload": payload,
    }
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record))
        handle.write("\n")


def write_checkpoint(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    checkpoint = {
        "timestamp": datetime.now(UTC).isoformat(),
        "payload": payload,
    }
    path.write_text(json.dumps(checkpoint, indent=2), encoding="utf-8")
