"""Near-miss refactor queue stub.

Generated by 80A_NEAR_MISS_REFACTOR_QUEUE_STUB.

Queue is contract-only.
No mutation, no training, no strategy DB write,
no promotion, no broker execution, no live trading.
"""

MAX_REFACTOR_ATTEMPTS = 3
QUEUE_WRITE_ENABLED = False
MUTATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def near_miss_queue_status() -> dict:
    return {
        "max_refactor_attempts": MAX_REFACTOR_ATTEMPTS,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def validate_attempt_count(attempt_count: int) -> dict:
    return {
        "attempt_count": attempt_count,
        "max_refactor_attempts": MAX_REFACTOR_ATTEMPTS,
        "allowed": 0 <= attempt_count <= MAX_REFACTOR_ATTEMPTS,
    }
