"""Real historical bar fetch service.

Generated by 77K_REAL_HISTORICAL_BAR_FETCH_SOURCE_CREATION.

This service defines the safe fetch boundary only.
Historical bar fetch remains disabled by gate.
No replay, training, strategy DB writes, promotion, broker, or live trading.
"""

from __future__ import annotations

from typing import Any

from backend.app.stacks.strategy_candidate_sandbox.L1_security_auth_safety.real_historical_bar_fetch_gate import (
    historical_bar_fetch_gate_status,
)


REQUIRED_BAR_FIELDS = ["symbol", "date", "open", "high", "low", "close", "volume"]


def get_fetch_gate_status() -> dict:
    return historical_bar_fetch_gate_status()


def validate_fetch_scope(symbols: list[str], max_rows: int) -> dict:
    gate = get_fetch_gate_status()
    allowlist = set(gate["symbol_allowlist"])

    valid = (
        len(symbols) <= gate["max_symbols_allowed"]
        and max_rows <= gate["max_rows_allowed"]
        and all(symbol in allowlist for symbol in symbols)
    )

    return {
        "valid": valid,
        "symbols": symbols,
        "max_rows": max_rows,
        "gate": gate,
    }


def validate_bar_schema(rows: list[dict[str, Any]]) -> dict:
    missing = []

    for index, row in enumerate(rows):
        for field in REQUIRED_BAR_FIELDS:
            if field not in row:
                missing.append({"row": index, "field": field})

    return {
        "valid": len(missing) == 0,
        "row_count": len(rows),
        "required_fields": REQUIRED_BAR_FIELDS,
        "missing": missing,
    }


def preview_fetch_contract(symbol: str = "VFV.TO", max_rows: int = 300) -> dict:
    scope = validate_fetch_scope([symbol], max_rows)

    return {
        "mode": "FETCH_CONTRACT_ONLY",
        "fetch_allowed_now": False,
        "symbol": symbol,
        "max_rows": max_rows,
        "period": "1y",
        "interval": "1d",
        "scope": scope,
        "safety": get_fetch_gate_status(),
    }


def future_fetch_single_symbol_bars(symbol: str = "VFV.TO", max_rows: int = 300) -> dict:
    gate = get_fetch_gate_status()

    if gate["historical_bar_fetch_enabled"] is not True:
        return {
            "fetch_executed": False,
            "blocked_by_gate": True,
            "reason": "historical_bar_fetch_enabled is False",
            "symbol": symbol,
            "max_rows": max_rows,
            "safety": gate,
        }

    raise RuntimeError("Historical bar fetch execution is not implemented in this phase")
