"""Repository replay input wire.

Generated by 119B_REPLAY_ENGINE_REPOSITORY_INPUT_WIRE.

This wires the replay engine to the approved research repository manifest.
It does not execute training.
It does not write to DB.
It does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
import json

REPOSITORY_TRAINING_MANIFEST = Path('/home/tkanhai/Neurovest/backend/app/stacks/learning_research/research_data/manifests/training/training_manifest_repository_v1.json')

REPLAY_REPOSITORY_INPUT_ENABLED = True
TRAINING_EXECUTION_ENABLED = False
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def wire_status() -> dict:
    return {
        "repository_training_manifest": str(REPOSITORY_TRAINING_MANIFEST),
        "replay_repository_input_enabled": REPLAY_REPOSITORY_INPUT_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def load_repository_training_manifest() -> dict:
    return json.loads(REPOSITORY_TRAINING_MANIFEST.read_text(encoding="utf-8"))


def preview_repository_replay_inputs() -> dict:
    manifest = load_repository_training_manifest()
    return {
        "mode": "REPOSITORY_REPLAY_INPUT_PREVIEW",
        "approved_for_training": manifest.get("approved_for_training"),
        "csv_file_count": manifest.get("csv_file_count"),
        "excluded_row_count": manifest.get("excluded_row_count"),
        "training_executed": False,
        "status": wire_status(),
    }
