"""Training read-only learner stub.

Generated by 82A_TRAINING_READ_ONLY_LEARNER_STUB.

Learner is read-only and disabled.
No training execution, no mutation, no queue writes,
no strategy DB writes, no promotion, no broker execution, no live trading.
"""

TRAINING_ENABLED = False
READ_ONLY_LEARNER_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def learner_status() -> dict:
    return {
        "training_enabled": TRAINING_ENABLED,
        "read_only_learner_enabled": READ_ONLY_LEARNER_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def preview_learning_input(report_id: str, candidate_id: str) -> dict:
    return {
        "mode": "PREVIEW_ONLY",
        "report_id": report_id,
        "candidate_id": candidate_id,
        "training_allowed_now": TRAINING_ENABLED,
        "mutation_allowed_now": MUTATION_ALLOWED,
        "write_allowed_now": LEARNER_WRITE_ENABLED,
        "status": learner_status(),
    }
