"""Fixture bar math contract functions.

Generated by 69B_FIXTURE_BAR_MATH_FUNCTION_SOURCE_CREATION.

These functions are pure math helpers only.
They do not run replay, score strategies, write strategy DB,
promote candidates, place broker orders, or enable live trading.
"""

from __future__ import annotations

from math import sqrt


REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def contract_status() -> dict:
    return {
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def calculate_simple_returns(close_prices: list[float]) -> list[float]:
    if len(close_prices) < 2:
        return []

    returns: list[float] = []
    for previous, current in zip(close_prices, close_prices[1:]):
        if previous == 0:
            returns.append(0.0)
        else:
            returns.append((current / previous) - 1.0)

    return returns


def calculate_cumulative_return(returns: list[float]) -> float:
    total = 1.0

    for value in returns:
        total *= 1.0 + value

    return total - 1.0


def calculate_rolling_mean(values: list[float], window: int) -> list[float | None]:
    if window <= 0:
        raise ValueError("window must be greater than zero")

    output: list[float | None] = []

    for index in range(len(values)):
        if index + 1 < window:
            output.append(None)
            continue

        section = values[index + 1 - window:index + 1]
        output.append(sum(section) / window)

    return output


def calculate_rolling_volatility(returns: list[float], window: int) -> list[float | None]:
    if window <= 0:
        raise ValueError("window must be greater than zero")

    output: list[float | None] = []

    for index in range(len(returns)):
        if index + 1 < window:
            output.append(None)
            continue

        section = returns[index + 1 - window:index + 1]
        mean = sum(section) / window
        variance = sum((value - mean) ** 2 for value in section) / window
        output.append(sqrt(variance))

    return output


def calculate_max_drawdown(equity_curve: list[float]) -> float:
    if not equity_curve:
        return 0.0

    peak = equity_curve[0]
    max_drawdown = 0.0

    for value in equity_curve:
        peak = max(peak, value)

        if peak == 0:
            drawdown = 0.0
        else:
            drawdown = (value / peak) - 1.0

        max_drawdown = min(max_drawdown, drawdown)

    return max_drawdown


def calculate_trade_count_proxy(signal_states: list[int]) -> int:
    if len(signal_states) < 2:
        return 0

    count = 0

    for previous, current in zip(signal_states, signal_states[1:]):
        if previous != current:
            count += 1

    return count
