"""Bulk historical data downloader stub.

Generated by 117A_BULK_HISTORICAL_DATA_DOWNLOADER_STUB.

This module defines the downloader contract only.
It does not download data yet.
It does not write to DB.
It does not train.
It does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, UTC
import json

DOWNLOADS_ENABLED = True
FILE_REPOSITORY_WRITES_ENABLED = True
DATABASE_WRITES_ALLOWED = False
TRAINING_EXECUTION_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def downloader_status() -> dict:
    return {
        "downloads_enabled": DOWNLOADS_ENABLED,
        "file_repository_writes_enabled": FILE_REPOSITORY_WRITES_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def load_bulk_download_plan(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def preview_download_batches(plan: dict) -> dict:
    batches = plan.get("batches", [])
    return {
        "mode": "DOWNLOAD_PREVIEW_ONLY",
        "plan_id": plan.get("plan_id"),
        "provider": plan.get("provider"),
        "total_symbols": plan.get("total_symbols"),
        "batch_count": len(batches),
        "downloads_executed": False,
        "status": downloader_status(),
    }


def build_symbol_dataset_manifest(
    symbol: str,
    asset_group: str,
    provider: str,
    interval: str,
    period: str,
    output_file: str,
    checksum_sha256: str | None = None,
    rows: int | None = None,
    first_date: str | None = None,
    last_date: str | None = None,
) -> dict:
    return {
        "dataset_id": f"YFINANCE_{asset_group.upper()}_{symbol.replace('.', '_').replace('^', '').replace('=', '_').replace('-', '_')}",
        "provider": provider,
        "asset_group": asset_group,
        "symbol": symbol,
        "interval": interval,
        "period": period,
        "output_file": output_file,
        "checksum_sha256": checksum_sha256,
        "rows": rows,
        "first_date": first_date,
        "last_date": last_date,
        "approved": False,
        "read_only": True,
        "normalized": False,
        "training_enabled": False,
        "created_at": datetime.now(UTC).isoformat(),
        "updated_at": datetime.now(UTC).isoformat(),
    }
