"""Manual activation gate.

Generated by 79A_MANUAL_ACTIVATION_GATE_STUB.

Manual activation is explicitly disabled.
This gate prevents automatic promotion, strategy DB writes,
training activation, broker execution, and live trading.
"""

MANUAL_ACTIVATION_ENABLED = False
AUTOMATIC_ACTIVATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def manual_activation_gate_status() -> dict:
    return {
        "manual_activation_enabled": MANUAL_ACTIVATION_ENABLED,
        "automatic_activation_allowed": AUTOMATIC_ACTIVATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
