"""Real historical bar fetch gate.

Generated by 77G_REAL_HISTORICAL_BAR_SOURCE_FETCH_GATE.

Historical bar fetch is still disabled by default.
This gate only defines the future safe fetch boundary.
"""

HISTORICAL_BAR_FETCH_ENABLED = False
REAL_HISTORICAL_REPLAY_ENABLED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

MAX_SYMBOLS_ALLOWED = 1
MAX_ROWS_ALLOWED = 300
SYMBOL_ALLOWLIST = ["VFV.TO"]


def historical_bar_fetch_gate_status() -> dict:
    return {
        "historical_bar_fetch_enabled": HISTORICAL_BAR_FETCH_ENABLED,
        "real_historical_replay_enabled": REAL_HISTORICAL_REPLAY_ENABLED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "max_symbols_allowed": MAX_SYMBOLS_ALLOWED,
        "max_rows_allowed": MAX_ROWS_ALLOWED,
        "symbol_allowlist": SYMBOL_ALLOWLIST,
    }
