"""Real historical replay dry-run gate.

Generated by 77B_REAL_HISTORICAL_REPLAY_DRY_RUN_GATE_STUB.

Real historical replay is explicitly disabled.
This gate must not enable training, strategy DB writes, promotion,
broker execution, or live trading.
"""

REAL_HISTORICAL_REPLAY_ENABLED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

MAX_SPECS_ALLOWED = 1
MAX_SYMBOLS_ALLOWED = 1
MAX_ROWS_ALLOWED = 300
INITIAL_SYMBOL_ALLOWLIST = ["VFV.TO"]


def real_historical_replay_gate_status() -> dict:
    return {
        "real_historical_replay_enabled": REAL_HISTORICAL_REPLAY_ENABLED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "max_specs_allowed": MAX_SPECS_ALLOWED,
        "max_symbols_allowed": MAX_SYMBOLS_ALLOWED,
        "max_rows_allowed": MAX_ROWS_ALLOWED,
        "initial_symbol_allowlist": INITIAL_SYMBOL_ALLOWLIST,
    }
