"""Training execution gate.

Generated by 85B_TRAINING_EXECUTION_GATE_STUB.

Training execution remains disabled.
Read-only learner inspection may be enabled elsewhere,
but this gate blocks training execution, writes, mutation,
queue writes, strategy DB writes, promotion, broker execution,
and live trading.
"""

TRAINING_EXECUTION_ENABLED = False
READ_ONLY_INPUT_ALLOWED = True
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def training_execution_gate_status() -> dict:
    return {
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "read_only_input_allowed": READ_ONLY_INPUT_ALLOWED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
