"""Training enablement gate.

Generated by 75A_TRAINING_GATE_STUB.

Training is explicitly disabled.
This gate must not enable learning, mutation, promotion,
strategy DB writes, broker execution, or live trading.
"""

TRAINING_ENABLED = False
SELF_MUTATION_ALLOWED = False
AUTONOMOUS_PROMOTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def training_gate_status() -> dict:
    return {
        "training_enabled": TRAINING_ENABLED,
        "self_mutation_allowed": SELF_MUTATION_ALLOWED,
        "autonomous_promotion_allowed": AUTONOMOUS_PROMOTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
