"""create canonical decision events table

Revision ID: ws3_stage5_decision_events
Revises:
Create Date: 2026-07-10 19:53:55.120241
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'ws3_stage5_decision_events'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_events',
    sa.Column('sequence_number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('causation_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(sequence_number = 1 AND previous_hash IS NULL) OR (sequence_number > 1 AND previous_hash IS NOT NULL)', name='ck_decision_events_previous_hash'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_decision_events_confidence_range'),
    sa.CheckConstraint('sequence_number >= 1', name='ck_decision_events_positive_sequence'),
    sa.PrimaryKeyConstraint('sequence_number'),
    sa.UniqueConstraint('content_hash', name='uq_decision_events_content_hash'),
    sa.UniqueConstraint('event_id', name='uq_decision_events_event_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_decision_events_idempotency_key')
    )
    op.create_index(op.f('ix_decision_events_causation_id'), 'decision_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_decision_events_correlation_id'), 'decision_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_decision_events_symbol'), 'decision_events', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_events_symbol'), table_name='decision_events')
    op.drop_index(op.f('ix_decision_events_correlation_id'), table_name='decision_events')
    op.drop_index(op.f('ix_decision_events_causation_id'), table_name='decision_events')
    op.drop_table('decision_events')
    # ### end Alembic commands ###
