"""Learning reward scorer.

Generated by 121F_LEARNING_REWARD_SCORER_STUB.

Scores replay decisions using next-bar movement only.
No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from typing import Any
import math

REWARD_SCORER_ENABLED = True
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

VALID_DECISIONS = {"BUY", "SELL", "HOLD"}


def _num(value: Any) -> float | None:
    try:
        number = float(value)
        if math.isfinite(number):
            return number
        return None
    except Exception:
        return None


def scorer_status() -> dict[str, Any]:
    return {
        "reward_scorer_enabled": REWARD_SCORER_ENABLED,
        "valid_decisions": sorted(VALID_DECISIONS),
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def score_decision_reward(
    decision: str,
    current_close: Any,
    next_close: Any,
) -> dict[str, Any]:
    decision = str(decision).upper()
    cur = _num(current_close)
    nxt = _num(next_close)

    if decision not in VALID_DECISIONS or cur is None or nxt is None or cur <= 0:
        return {
            "reward": 0.0,
            "confidence": 0.0,
            "next_return": None,
            "valid_reward": False,
            "reason": "invalid reward input",
        }

    next_return = (nxt / cur) - 1.0

    if decision == "BUY":
        reward = next_return
    elif decision == "SELL":
        reward = -next_return
    else:
        reward = -abs(next_return) * 0.1

    confidence = min(1.0, abs(next_return) * 50.0)

    return {
        "reward": float(reward),
        "confidence": float(confidence),
        "next_return": float(next_return),
        "valid_reward": True,
        "reason": "next-bar reward scored",
    }


def validate_reward_score(score: dict[str, Any]) -> bool:
    required = {"reward", "confidence", "next_return", "valid_reward", "reason"}
    if set(score.keys()) != required:
        return False

    if score.get("valid_reward") is not True:
        return False

    reward = _num(score.get("reward"))
    confidence = _num(score.get("confidence"))

    if reward is None or confidence is None:
        return False

    if not (0.0 <= confidence <= 1.0):
        return False

    return (
        DATABASE_WRITES_ALLOWED is False
        and STRATEGY_DB_WRITE_ALLOWED is False
        and PROMOTION_ENABLED is False
        and BROKER_EXECUTION_ENABLED is False
        and LIVE_EXECUTION_ENABLED is False
    )
