"""Learning artifact contract.

Generated by 121D_LEARNING_ARTIFACT_CONTRACT_STUB.

Defines the read-only learning artifact shape used by repository replay.
No DB writes.
No strategy promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
    "source_csv_modification_allowed": False,
}

LEARNING_ARTIFACT_CONTRACT_KEYS = {
    "artifact_id",
    "run_id",
    "symbol",
    "date",
    "cycle",
    "features",
    "decision",
    "reward",
    "confidence",
    "source",
    "safety_locks",
    "created_at",
}

VALID_DECISIONS = {"BUY", "SELL", "HOLD"}


def build_learning_artifact_contract(
    run_id: str,
    symbol: str,
    date: str,
    cycle: int,
    features: dict[str, Any],
    decision: str,
    reward: float | None = None,
    confidence: float | None = None,
    source: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "artifact_id": f"{run_id}:{symbol}:{date}:{cycle}",
        "run_id": run_id,
        "symbol": symbol,
        "date": date,
        "cycle": cycle,
        "features": features,
        "decision": decision,
        "reward": reward,
        "confidence": confidence,
        "source": source or {},
        "safety_locks": dict(SAFETY_LOCKS),
        "created_at": datetime.now(UTC).isoformat(),
    }


def validate_learning_artifact_contract(artifact: dict[str, Any]) -> bool:
    if set(artifact.keys()) != LEARNING_ARTIFACT_CONTRACT_KEYS:
        return False

    if artifact.get("decision") not in VALID_DECISIONS:
        return False

    if not isinstance(artifact.get("features"), dict):
        return False

    if artifact.get("reward") is not None and not isinstance(artifact.get("reward"), (int, float)):
        return False

    if artifact.get("confidence") is not None:
        confidence = artifact.get("confidence")
        if not isinstance(confidence, (int, float)):
            return False
        if not (0.0 <= float(confidence) <= 1.0):
            return False

    locks = artifact.get("safety_locks", {})
    return (
        locks.get("database_writes_allowed") is False
        and locks.get("strategy_db_write_allowed") is False
        and locks.get("promotion_enabled") is False
        and locks.get("broker_execution_enabled") is False
        and locks.get("live_execution_enabled") is False
        and locks.get("source_csv_modification_allowed") is False
    )


def build_empty_learning_artifact_contract() -> dict[str, Any]:
    return build_learning_artifact_contract(
        run_id="EMPTY",
        symbol="EMPTY",
        date="1970-01-01",
        cycle=0,
        features={},
        decision="HOLD",
        reward=None,
        confidence=None,
        source={"empty_contract": True},
    )
