"""Learning feature extractor.

Generated by 121E_LEARNING_FEATURE_EXTRACTOR_STUB.

Creates read-only feature vectors from replay OHLCV rows.
No source CSV mutation.
No DB writes.
No broker/live execution.
"""

from __future__ import annotations

from typing import Any
import math

FEATURE_EXTRACTOR_ENABLED = True
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False
SOURCE_CSV_MODIFICATION_ALLOWED = False

FEATURE_KEYS = {
    "open",
    "high",
    "low",
    "close",
    "volume",
    "intraday_return",
    "range_pct",
    "close_position_in_range",
    "previous_close",
    "daily_return",
    "valid_numeric_row",
}


def _num(value: Any) -> float | None:
    try:
        number = float(value)
        if math.isfinite(number):
            return number
        return None
    except Exception:
        return None


def extractor_status() -> dict[str, Any]:
    return {
        "feature_extractor_enabled": FEATURE_EXTRACTOR_ENABLED,
        "feature_keys": sorted(FEATURE_KEYS),
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "source_csv_modification_allowed": SOURCE_CSV_MODIFICATION_ALLOWED,
    }


def extract_learning_features(row: dict[str, Any], previous_close: float | None = None) -> dict[str, Any]:
    open_price = _num(row.get("open"))
    high = _num(row.get("high"))
    low = _num(row.get("low"))
    close = _num(row.get("close"))
    volume = _num(row.get("volume"))

    valid = all(v is not None for v in [open_price, high, low, close, volume])

    intraday_return = None
    range_pct = None
    close_position_in_range = None
    daily_return = None

    if valid:
        if open_price and open_price > 0:
            intraday_return = (close / open_price) - 1.0

        if low is not None and high is not None and close is not None:
            if high > low:
                range_pct = (high - low) / close if close and close > 0 else None
                close_position_in_range = (close - low) / (high - low)

        if previous_close is not None and previous_close > 0:
            daily_return = (close / previous_close) - 1.0

    return {
        "open": open_price,
        "high": high,
        "low": low,
        "close": close,
        "volume": volume,
        "intraday_return": intraday_return,
        "range_pct": range_pct,
        "close_position_in_range": close_position_in_range,
        "previous_close": previous_close,
        "daily_return": daily_return,
        "valid_numeric_row": valid,
    }


def validate_learning_features(features: dict[str, Any]) -> bool:
    if set(features.keys()) != FEATURE_KEYS:
        return False

    if features.get("valid_numeric_row") is not True:
        return False

    for key, value in features.items():
        if key == "valid_numeric_row":
            continue
        if value is not None:
            try:
                if not math.isfinite(float(value)):
                    return False
            except Exception:
                return False

    return (
        DATABASE_WRITES_ALLOWED is False
        and STRATEGY_DB_WRITE_ALLOWED is False
        and PROMOTION_ENABLED is False
        and BROKER_EXECUTION_ENABLED is False
        and LIVE_EXECUTION_ENABLED is False
        and SOURCE_CSV_MODIFICATION_ALLOWED is False
    )
