"""Market Regime Library.

Generated by 127A_MARKET_REGIME_LIBRARY_STUB.

Read-only regime definitions used by replay learning.

No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False

SAFETY_LOCKS={
    "database_writes_allowed":False,
    "strategy_db_write_allowed":False,
    "promotion_enabled":False,
    "broker_execution_enabled":False,
    "live_execution_enabled":False,
}

REGIME_LIBRARY={

    "BULLISH_MOMENTUM":{
        "trend":"UP",
        "volatility":"NORMAL",
        "risk":"MEDIUM",
    },

    "BEARISH_TREND":{
        "trend":"DOWN",
        "volatility":"NORMAL",
        "risk":"HIGH",
    },

    "SIDEWAYS_RANGE":{
        "trend":"FLAT",
        "volatility":"LOW",
        "risk":"LOW",
    },

    "HIGH_VOLATILITY":{
        "trend":"ANY",
        "volatility":"HIGH",
        "risk":"HIGH",
    },

    "LOW_VOLATILITY":{
        "trend":"ANY",
        "volatility":"LOW",
        "risk":"LOW",
    },
}

def regime_library_status()->dict[str,Any]:

    return{
        "enabled":True,
        "regimes":sorted(REGIME_LIBRARY.keys()),
        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }

def get_market_regime(name:str)->dict[str,Any]|None:
    return REGIME_LIBRARY.get(str(name).upper())

def list_market_regimes()->list[str]:
    return sorted(REGIME_LIBRARY.keys())
