"""Symbol Intelligence Profile.

Generated by 126A_SYMBOL_INTELLIGENCE_PROFILE_STUB.

Creates read-only symbol intelligence profiles from learning artifacts,
strategy knowledge, and indicator knowledge graphs.

No database writes.
No strategy promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
}

PROFILE_KEYS = {
    "symbol",
    "profile_id",
    "asset_class",
    "strategy_families",
    "strategies",
    "indicators",
    "regimes",
    "average_reward",
    "average_confidence",
    "observations",
    "evidence",
    "safety_locks",
    "created_at",
}

def profile_status() -> dict[str, Any]:
    return {
        "symbol_profile_enabled": True,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }

def build_symbol_intelligence_profile(
    *,
    symbol: str,
    knowledge_objects: list[dict[str, Any]],
) -> dict[str, Any]:

    strategy_families=set()
    strategies=set()
    indicators=set()
    regimes=set()
    evidence=[]
    rewards=[]
    confidence=[]

    for obj in knowledge_objects:

        if symbol not in (obj.get("symbols") or []):
            continue

        strategy_families.add(obj.get("strategy_family","UNKNOWN"))
        strategies.add(obj.get("strategy_name","UNKNOWN"))

        indicators.update(obj.get("indicators") or [])
        regimes.update(obj.get("regimes") or [])

        for e in obj.get("evidence",[]):
            evidence.append(e)

        for s in obj.get("source_artifacts",[]):
            r=s.get("reward")
            if isinstance(r,(int,float)):
                rewards.append(float(r))

        c=obj.get("confidence")
        if isinstance(c,(int,float)):
            confidence.append(float(c))

    avg_reward=(
        sum(rewards)/len(rewards)
        if rewards else None
    )

    avg_conf=(
        sum(confidence)/len(confidence)
        if confidence else 0.0
    )

    return {

        "symbol":symbol,
        "profile_id":f"SYMBOL_PROFILE:{symbol}",
        "asset_class":"UNKNOWN",

        "strategy_families":sorted(strategy_families),
        "strategies":sorted(strategies),
        "indicators":sorted(indicators),
        "regimes":sorted(regimes),

        "average_reward":avg_reward,
        "average_confidence":avg_conf,

        "observations":len(evidence),

        "evidence":evidence,

        "safety_locks":dict(SAFETY_LOCKS),

        "created_at":datetime.now(UTC).isoformat(),
    }

def validate_symbol_intelligence_profile(profile:dict[str,Any])->bool:

    if set(profile.keys())!=PROFILE_KEYS:
        return False

    if not profile.get("symbol"):
        return False

    if not isinstance(profile.get("strategies"),list):
        return False

    if not isinstance(profile.get("indicators"),list):
        return False

    if not isinstance(profile.get("regimes"),list):
        return False

    locks=profile.get("safety_locks",{})

    return (

        locks.get("database_writes_allowed") is False
        and
        locks.get("strategy_db_write_allowed") is False
        and
        locks.get("promotion_enabled") is False
        and
        locks.get("broker_execution_enabled") is False
        and
        locks.get("live_execution_enabled") is False
    )
