"""
Training Observability Contract

Generated by 128B_TRAINING_OBSERVABILITY_CONTRACT

Read Only

Replay
Paper Trading
Future Live Analytics

No DB Writes
No Broker
No Promotion
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False

TRAINING_METRICS={

"replay_metadata":[
"replay_id",
"run_uuid",
"git_commit",
"training_profile",
"dataset_version",
"start_time",
"end_time",
"duration",
],

"dataset_health":[
"symbols_loaded",
"bars_loaded",
"missing_bars",
"duplicate_bars",
"bad_rows",
"skipped_rows",
],

"cycle_statistics":[
"cycle",
"processing_time_ms",
"bars_processed",
"features_generated",
"knowledge_generated",
],

"decision_ledger":[
"timestamp",
"cycle",
"symbol",
"decision",
"strategy",
"confidence",
"reward",
"risk_score",
"market_regime",
"reason",
],

"action_statistics":[
"buy_count",
"sell_count",
"hold_count",
"skip_count",
],

"strategy_statistics":[
"wins",
"losses",
"profit_factor",
"expectancy",
"sharpe",
"sortino",
"max_drawdown",
],

"indicator_statistics":[
"usage",
"accuracy",
"average_reward",
"best_symbol",
"best_regime",
],

"symbol_profiles":[
"average_reward",
"average_confidence",
"best_strategy",
"best_regime",
],

"market_regimes":[
"year",
"month",
"week",
"day",
"hour",
],

"equity_curve":[
"equity",
"drawdown",
"rolling_reward",
"rolling_win_rate",
"rolling_sharpe",
"rolling_sortino",
],

"confidence_calibration":[
"predicted_confidence",
"actual_accuracy",
"brier_score",
],

"knowledge_growth":[
"artifacts",
"knowledge_objects",
"graph_nodes",
"graph_edges",
"research_links",
],

"performance":[
"cpu_percent",
"ram_percent",
"bars_per_second",
"rows_per_second",
],

"training_health":[
"overall_score",
"learning_score",
"data_quality",
"risk_score",
],
}

def observability_status()->dict[str,Any]:

    return{

        "enabled":True,

        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }

def required_sections()->list[str]:
    return sorted(TRAINING_METRICS.keys())

def required_metrics(section:str)->list[str]:
    return TRAINING_METRICS.get(section,[])

def create_empty_report()->dict[str,Any]:

    report={

        "created_at":datetime.now(UTC).isoformat(),

        "status":observability_status(),

        "sections":{},
    }

    for section,metrics in TRAINING_METRICS.items():

        report["sections"][section]={

            metric:None

            for metric in metrics
        }

    return report
