from __future__ import annotations

import json
import os
import py_compile
import subprocess
import urllib.request
from pathlib import Path

from spine.L4_runtime.compiler.contract_diff_engine import compute_contract_diff
from spine.L4_runtime.compiler.contract_patch_engine import generate_contract_patch_plan
from spine.L4_runtime.compiler.execution_gate import validate_stage


MODEL = os.environ.get("NEURO_MODEL", "llama3.1:latest")

WIRING_FILE = "backend/app/spine/L3_facade/stack_wiring_facade.py"
WIRING_TEST = "backend/app/spine/L7_tests/test_stack_wiring_facade.py"
DOMAIN_TEST = "backend/app/spine/L7_tests/test_domain_logic_flow.py"
FACADE_FILE = "backend/app/spine/L3_facade/domain_flow_facade.py"
FACADE_TEST = "backend/app/spine/L7_tests/test_domain_flow_facade.py"


DOMAIN_FILES = [
    "backend/app/stacks/market_data/price.py",
    "backend/app/stacks/market_data/bars.py",
    "backend/app/stacks/market_data/feed.py",
    "backend/app/stacks/risk/exposure.py",
    "backend/app/stacks/risk/limits.py",
    "backend/app/stacks/risk/kill_switch.py",
    "backend/app/stacks/strategy/signal.py",
    "backend/app/stacks/strategy/engine.py",
    "backend/app/stacks/portfolio/allocator.py",
    "backend/app/stacks/portfolio/rebalance.py",
    "backend/app/stacks/journal_ledger/record.py",
    "backend/app/stacks/journal_ledger/ledger.py",
    DOMAIN_TEST,
]


IMPROVEMENT_ROADMAP = [
    "Replace stub tests with real assertions",
    "Replace AUTO GENERATED fallback files with real implementations",
    "Add end-to-end topology proof tests",
    "Add facade wiring verification tests",
    "Add SnapTrade dry-run adapter tests",
    "Add paper broker PnL validation tests",
    "Add regime simulator scenarios",
    "Add Monte Carlo statistical validation",
    "Add strategy evolution scoring verification",
    "Add WolfDen routing proof tests",
    "Add chat persistence verification",
    "Add frontend integration verification",
    "Add runtime performance benchmarks",
    "Add architecture drift detection proofs",
]


class Neuro:


    def next_quality_task(self):
        tasks = [
            "replace_stub_tests",
            "replace_autogenerated_fallbacks",
            "add_topology_proof_tests",
            "add_facade_wiring_tests",
            "add_snaptrade_dry_run_tests",
            "add_pnl_validation_tests",
            "add_regime_simulation_tests",
            "add_monte_carlo_validation",
            "add_strategy_scoring_tests",
            "add_wolfden_routing_tests",
            "add_chat_persistence_tests",
            "add_frontend_integration_tests",
            "add_performance_benchmarks",
            "add_drift_detection"
        ]

        if not hasattr(self, "_quality_index"):
            self._quality_index = 0

        if self._quality_index >= len(tasks):
            return "QUALITY_COMPLETE"

        task = tasks[self._quality_index]
        self._quality_index += 1
        return task

    def __init__(self):
        self.pending_plan = []
        self.pending_reason = ""
        self.last_built = []
        self.memory_file = Path("backend/app/spine/L5_api/.neuro_memory.json")
        self.memory = self.load_memory()

    # ---------------- MEMORY ----------------

    def load_memory(self):
        if self.memory_file.exists():
            return json.loads(self.memory_file.read_text())
        return {"completed_phases": [], "failed_phases": [], "last_built": []}

    def save_memory(self):
        self.memory_file.write_text(json.dumps(self.memory, indent=2))

    # ---------------- OLLAMA ----------------

    def ollama(self, user: str, context: dict) -> str:
        payload = {
            "model": MODEL,
            "stream": False,
            "options": {"num_predict": 160, "temperature": 0.1},
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are Neuro, a repo-aware architecture planner. "
                        "Be concise. No execution without approval."
                    ),
                },
                {
                    "role": "user",
                    "content": f"{user}\n\n{json.dumps(context, indent=2)}",
                },
            ],
        }

        try:
            req = urllib.request.Request(
                "http://localhost:11434/api/chat",
                data=json.dumps(payload).encode(),
                headers={"Content-Type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=6) as r:
                data = json.loads(r.read().decode())
            return data.get("message", {}).get("content", "")
        except Exception as e:
            return f"LLM unavailable: {e}"

    # ---------------- CONTEXT ----------------

    def repo_context(self):
        diff = compute_contract_diff(limit=500)
        patch = generate_contract_patch_plan(limit=500).get("patch_plan", [])
        return {
            "missing_contract_groups": len(diff["missing"]),
            "extra_drift_groups": len(diff["extra"]),
            "next_contract_actions": [p["file"] for p in patch[:5]],
            "wiring_file_exists": Path(WIRING_FILE).exists(),
            "wiring_test_exists": Path(WIRING_TEST).exists(),
            "facade_file_exists": Path(FACADE_FILE).exists(),
            "facade_test_exists": Path(FACADE_TEST).exists(),
        }

    # ---------------- DOMAIN CHECK ----------------

    def domain_complete(self):
        for f in DOMAIN_FILES:
            p = Path(f)
            if not p.exists():
                return False
            if "DOMAIN_LOGIC_V1" not in p.read_text(errors="ignore"):
                return False
        return True

    # ---------------- ROADMAP ----------------

    def improvement_plan(self):
        return "\n".join(
            ["SYSTEM IMPROVEMENT ROADMAP", "==========================", ""]
            + [f"{i+1}. {x}" for i, x in enumerate(IMPROVEMENT_ROADMAP)]
            + ["", "Build roadmap: COMPLETE", "Quality roadmap: ACTIVE"]
        )

    def quality_plan(self):
        return self.next_quality_task()

    # ---------------- STATUS ----------------

    def status(self):
        ctx = self.repo_context()
        return (
            "STATUS\n"
            f"- Missing contracts: {ctx['missing_contract_groups']}\n"
            f"- Drift groups: {ctx['extra_drift_groups']}\n"
            f"- Wiring: {ctx['wiring_file_exists']}\n"
            f"- Facade: {ctx['facade_file_exists']}\n"
        )

    # ---------------- TESTS ----------------

    def run_tests(self):
        r = subprocess.run(
            ["pytest", "-q", "backend/app/spine/L7_tests"],
            text=True,
            capture_output=True,
        )
        return r.stdout + "\n" + r.stderr

    # ---------------- PLANNING ----------------

    def next_phase(self):
        if not self.domain_complete():
            return "DOMAIN INCOMPLETE"

        return None

    def plan_next(self, user: str):
        ctx = self.repo_context()
        llm = self.ollama(user, ctx)

        if not self.pending_plan:
            phase = self.next_phase()
            if phase:
                return phase
            return self.next_quality_task()

        lines = ["PLAN READY", self.pending_reason, "", "Files:"]
        for i, p in enumerate(self.pending_plan):
            lines.append(f"{i+1}. {p}")

        lines.append("\nLLM:")
        lines.append(llm)

        return "\n".join(lines)

    # ---------------- APPROVAL ----------------

    def approve(self):
        if not self.pending_plan:
            return "No pending plan"

        results = []

        for f in self.pending_plan:
            path = Path(f)
            path.parent.mkdir(parents=True, exist_ok=True)

            if not path.exists():
                path.write_text('"""AUTO GENERATED"""\n')

            py_compile.compile(str(path), doraise=True)
            self.last_built.append(str(path))
            results.append(f"BUILT {path}")

        self.pending_plan = []
        self.pending_reason = ""

        test_output = self.run_tests()

        return "\n".join(results) + "\n\n" + test_output

    # ---------------- CHAT ROUTER ----------------

    def chat(self, user: str):
        m = user.lower()

        if "test" in m:
            return self.run_tests()

        if "approve" in m:
            return self.approve()

        if "status" in m:
            return self.status()

        if "progress" in m:
            return self.next_quality_task()

        if "quality" in m:
            return self.next_quality_task()

        if "build" in m or "next" in m:
            return self.plan_next(user)

        return self.ollama(user, self.repo_context())


def run():
    n = Neuro()
    print("NEURO ONLINE")

    while True:
        u = input("\nyou > ")
        if u in {"exit", "quit"}:
            break
        print("\nneuro >")
        print(n.chat(u))


if __name__ == "__main__":
    run()
