#!/bin/bash
set -e

echo "🧠 Building Repo Intelligence Phase V6 (Autonomous Apply + Convergence Loop)..."

mkdir -p backend/app/spine/L4_runtime
mkdir -p backend/app/spine/L5_api
mkdir -p backend/app/spine/L7_tests
mkdir -p backend/app/spine/L4_runtime/applied_patches

# =========================================================
# FILE 1 — PATCH EXECUTOR (SAFE APPLY ENGINE)
# =========================================================
cat > backend/app/spine/L4_runtime/patch_executor.py <<'PY'
from __future__ import annotations

from pathlib import Path
import json
import time

from spine.L4_runtime.architecture_repair_engine import detect_repair_actions
from spine.L4_runtime.stack_gap_analyzer import analyze_stack_gaps

ROOT = Path(".").resolve()
PATCH_LOG = ROOT / "backend/app/spine/L4_runtime/applied_patches/patch_log.jsonl"

def apply_patch(action: dict) -> dict:
    """
    SAFE PATCH EXECUTOR:
    - ONLY creates missing scaffold files
    - NEVER deletes or modifies existing logic
    """

    if action.get("type") != "MISSING_COMPONENT":
        return {"status": "skipped", "reason": "non-applicable action"}

    target_path = ROOT / action["action"].replace("CREATE ", "")

    target_path.parent.mkdir(parents=True, exist_ok=True)

    content = f'''"""
AUTO-APPLIED PATCH (PHASE 6)
STACK: {action["stack"]}
COMPONENT: {action["target"]}

GENERATED BY AUTONOMOUS ENGINE
"""

def init():
    raise NotImplementedError("Auto-generated placeholder: {action["target"]}")
'''

    target_path.write_text(content)

    log_entry = {
        "timestamp": time.time(),
        "action": action,
        "path": str(target_path)
    }

    with open(PATCH_LOG, "a") as f:
        f.write(json.dumps(log_entry) + "\n")

    return {
        "status": "applied",
        "path": str(target_path)
    }

def run_patch_cycle(limit: int = 1000) -> dict:
    repairs = detect_repair_actions(limit=limit)["repairs"]

    results = []

    for r in repairs:
        results.append(apply_patch(r))

    return {
        "applied_count": len([r for r in results if r["status"] == "applied"]),
        "total_actions": len(repairs),
        "results": results
    }

if __name__ == "__main__":
    import json
    print(json.dumps(run_patch_cycle(), indent=2))
PY


# =========================================================
# FILE 2 — CONVERGENCE ENGINE (STOP CONDITION)
# =========================================================
cat > backend/app/spine/L4_runtime/convergence_engine.py <<'PY'
from __future__ import annotations

from spine.L4_runtime.repo_intelligence_engine import build_repo_intelligence
from spine.L4_runtime.stack_gap_analyzer import analyze_stack_gaps
from spine.L4_runtime.dependency_graph_engine import build_dependency_graph

def check_convergence(limit: int = 1000) -> dict:
    intel = build_repo_intelligence(limit=limit)
    gaps = analyze_stack_gaps(limit=limit)
    deps = build_dependency_graph(limit=limit)

    has_gaps = len(gaps["gaps"]) > 0
    has_missing_deps = len(deps["missing_links"]) > 0

    converged = not has_gaps and not has_missing_deps

    return {
        "converged": converged,
        "gap_count": len(gaps["gaps"]),
        "missing_dependency_count": len(deps["missing_links"])
    }
PY


# =========================================================
# FILE 3 — SAFE AUTONOMOUS LOOP CONTROLLER
# =========================================================
cat > backend/app/spine/L4_runtime/autonomous_repair_loop.py <<'PY'
from __future__ import annotations

import time

from spine.L4_runtime.patch_executor import run_patch_cycle
from spine.L4_runtime.convergence_engine import check_convergence

MAX_CYCLES = 5

def run_autonomous_loop(limit: int = 1000) -> dict:
    """
    SAFE CONTROLLED AUTONOMOUS LOOP:
    - bounded cycles
    - convergence check
    - no infinite execution
    """

    cycle = 0
    history = []

    while cycle < MAX_CYCLES:
        patch_result = run_patch_cycle(limit=limit)
        state = check_convergence(limit=limit)

        history.append({
            "cycle": cycle,
            "patched": patch_result,
            "state": state
        })

        if state["converged"]:
            break

        cycle += 1
        time.sleep(0.1)

    return {
        "cycles_run": cycle + 1,
        "final_state": history[-1]["state"],
        "history": history
    }

if __name__ == "__main__":
    import json
    print(json.dumps(run_autonomous_loop(), indent=2))
PY


# =========================================================
# FILE 4 — CLI V6 (FULL AUTONOMOUS ENGINE)
# =========================================================
cat > backend/app/spine/L5_api/repo_intelligence_v6_cli.py <<'PY'
from __future__ import annotations

import json

from spine.L4_runtime.repo_intelligence_engine import build_repo_intelligence
from spine.L4_runtime.stack_gap_analyzer import analyze_stack_gaps
from spine.L4_runtime.dependency_graph_engine import build_dependency_graph
from spine.L4_runtime.runtime_wiring_validator import validate_runtime_wiring
from spine.L4_runtime.implementation_planner_v4 import compute_next_implementation
from spine.L4_runtime.architecture_repair_engine import detect_repair_actions
from spine.L4_runtime.stack_rebalancer import compute_rebalance_actions
from spine.L4_runtime.autonomous_repair_loop import run_autonomous_loop
from spine.L4_runtime.convergence_engine import check_convergence

def run(limit: int = 1000):
    report = {
        "repo_intelligence": build_repo_intelligence(limit=limit),
        "stack_gaps": analyze_stack_gaps(limit=limit),
        "dependency_graph": build_dependency_graph(limit=limit),
        "wiring_validation": validate_runtime_wiring(limit=limit),
        "next_action": compute_next_implementation(limit=limit),
        "repair_actions": detect_repair_actions(limit=limit),
        "rebalance_actions": compute_rebalance_actions(limit=limit),

        # 🔥 PHASE 6 AUTONOMY LAYER
        "convergence_precheck": check_convergence(limit=limit),
        "autonomous_loop": run_autonomous_loop(limit=limit),
    }

    print(json.dumps(report, indent=2))

if __name__ == "__main__":
    run()
PY


# =========================================================
# FILE 5 — PHASE 6 TESTS (SAFETY + CONVERGENCE)
# =========================================================
cat > backend/app/spine/L7_tests/test_phase6_autonomy.py <<'PY'
from spine.L4_runtime.patch_executor import run_patch_cycle
from spine.L4_runtime.convergence_engine import check_convergence
from spine.L4_runtime.autonomous_repair_loop import run_autonomous_loop

def test_patch_executor_runs():
    r = run_patch_cycle(limit=200)
    assert "applied_count" in r

def test_convergence_engine_runs():
    c = check_convergence(limit=200)
    assert "converged" in c

def test_autonomous_loop_runs():
    r = run_autonomous_loop(limit=200)
    assert "cycles_run" in r
    assert "final_state" in r
PY


# =========================================================
# EXECUTION
# =========================================================

echo "🧠 Running Phase 6 CLI..."
PYTHONPATH=backend/app python3 backend/app/spine/L5_api/repo_intelligence_v6_cli.py

echo "🧪 Running Phase 6 tests..."
PYTHONPATH=backend/app pytest -q backend/app/spine/L7_tests/test_phase6_autonomy.py

echo "✅ Repo Intelligence Phase V6 Complete"
