#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()

ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "eight_hour_replay_training"

TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L4_runtime_orchestration/replay_execution_engine.py"

OUT_DIR = ARCH / "replay_execution_engine_contract"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "129D_replay_execution_engine_contract_latest.json"
OUT_TXT  = OUT_DIR / "129D_replay_execution_engine_contract_latest.txt"

PHASE="129D_REPLAY_EXECUTION_ENGINE_CONTRACT"

SOURCE_TEXT = '''"""
Replay Execution Engine

Generated by 129D_REPLAY_EXECUTION_ENGINE_CONTRACT

Historical Replay Only

NO DATABASE WRITES
NO STRATEGY PROMOTION
NO BROKER
NO LIVE EXECUTION
"""

from __future__ import annotations

from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False

ENGINE_ENABLED=True

PIPELINE_STAGES=[

"load_row",
"feature_extraction",
"decision_generation",
"reward_scoring",
"artifact_generation",
"decision_ledger",
"cycle_ledger",
"equity_curve",
"knowledge_growth",
"heartbeat",
"checkpoint",

]

def engine_status()->dict[str,Any]:

    return{

        "enabled":ENGINE_ENABLED,

        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,

        "pipeline":PIPELINE_STAGES,
    }


def build_execution_plan(

    *,
    run_id:str,
    symbols:list[str],
    duration_hours:int,

)->dict[str,Any]:

    return{

        "run_id":run_id,

        "symbols":symbols,

        "symbol_count":len(symbols),

        "duration_hours":duration_hours,

        "pipeline":PIPELINE_STAGES,

        "heartbeat_seconds":30,

        "checkpoint_seconds":300,

        "decision_logging":True,

        "equity_curve_logging":True,

        "knowledge_logging":True,

        "performance_logging":True,

        "database_writes_allowed":False,

        "broker_execution_enabled":False,

        "live_execution_enabled":False,

    }
'''

def read_json(path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}

TARGET.parent.mkdir(parents=True,exist_ok=True)
TARGET.write_text(SOURCE_TEXT,encoding="utf-8")

compile_ok=False
compile_error=None

try:
    py_compile.compile(str(TARGET),doraise=True)
    compile_ok=True
except Exception as exc:
    compile_error=str(exc)

text=TARGET.read_text()

checks={

"target_exists":TARGET.exists(),
"compile_ok":compile_ok,

"engine_status":"engine_status" in text,
"execution_plan":"build_execution_plan" in text,
"pipeline":"PIPELINE_STAGES" in text,

"db_blocked":"DATABASE_WRITES_ALLOWED=False" in text,
"broker_blocked":"BROKER_EXECUTION_ENABLED=False" in text,
"live_blocked":"LIVE_EXECUTION_ENABLED=False",

}

result={

"phase":PHASE,
"created_at":datetime.now(UTC).isoformat(),

"checks":checks,

"compile_error":compile_error,

"recommended_next_phase":"129E_REPLAY_EXECUTION_ENGINE_IMPLEMENTATION",

"certified":all(checks.values()),

}

OUT_JSON.write_text(json.dumps(result,indent=2),encoding="utf-8")

OUT_TXT.write_text(
"\n".join([
PHASE,
"",
f"certified: {result['certified']}",
f"compile_ok: {compile_ok}",
"",
"Replay execution engine contract created.",
"",
"Stages:",
"load_row",
"feature_extraction",
"decision_generation",
"reward_scoring",
"artifact_generation",
"decision_ledger",
"cycle_ledger",
"equity_curve",
"knowledge_growth",
"heartbeat",
"checkpoint",
"",
"Next:",
result["recommended_next_phase"],
]),
encoding="utf-8",
)

print(json.dumps({

"phase":PHASE,
"certified":result["certified"],
"compile_ok":compile_ok,
"recommended_next_phase":result["recommended_next_phase"],
"out_json":str(OUT_JSON),
"out_txt":str(OUT_TXT),

},indent=2))
