#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "real_historical_bar_fetch_source_creation_preview" / "77J_real_historical_bar_fetch_source_creation_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/real_historical_bar_fetch_service.py"

OUT_DIR = ARCH / "real_historical_bar_fetch_source_creation"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "77K_real_historical_bar_fetch_source_creation_latest.json"
OUT_TXT = OUT_DIR / "77K_real_historical_bar_fetch_source_creation_latest.txt"

PHASE = "77K_REAL_HISTORICAL_BAR_FETCH_SOURCE_CREATION"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Real historical bar fetch service.

Generated by 77K_REAL_HISTORICAL_BAR_FETCH_SOURCE_CREATION.

This service defines the safe fetch boundary only.
Historical bar fetch remains disabled by gate.
No replay, training, strategy DB writes, promotion, broker, or live trading.
"""

from __future__ import annotations

from typing import Any

from backend.app.stacks.strategy_candidate_sandbox.L1_security_auth_safety.real_historical_bar_fetch_gate import (
    historical_bar_fetch_gate_status,
)


REQUIRED_BAR_FIELDS = ["symbol", "date", "open", "high", "low", "close", "volume"]


def get_fetch_gate_status() -> dict:
    return historical_bar_fetch_gate_status()


def validate_fetch_scope(symbols: list[str], max_rows: int) -> dict:
    gate = get_fetch_gate_status()
    allowlist = set(gate["symbol_allowlist"])

    valid = (
        len(symbols) <= gate["max_symbols_allowed"]
        and max_rows <= gate["max_rows_allowed"]
        and all(symbol in allowlist for symbol in symbols)
    )

    return {
        "valid": valid,
        "symbols": symbols,
        "max_rows": max_rows,
        "gate": gate,
    }


def validate_bar_schema(rows: list[dict[str, Any]]) -> dict:
    missing = []

    for index, row in enumerate(rows):
        for field in REQUIRED_BAR_FIELDS:
            if field not in row:
                missing.append({"row": index, "field": field})

    return {
        "valid": len(missing) == 0,
        "row_count": len(rows),
        "required_fields": REQUIRED_BAR_FIELDS,
        "missing": missing,
    }


def preview_fetch_contract(symbol: str = "VFV.TO", max_rows: int = 300) -> dict:
    scope = validate_fetch_scope([symbol], max_rows)

    return {
        "mode": "FETCH_CONTRACT_ONLY",
        "fetch_allowed_now": False,
        "symbol": symbol,
        "max_rows": max_rows,
        "period": "1y",
        "interval": "1d",
        "scope": scope,
        "safety": get_fetch_gate_status(),
    }


def future_fetch_single_symbol_bars(symbol: str = "VFV.TO", max_rows: int = 300) -> dict:
    gate = get_fetch_gate_status()

    if gate["historical_bar_fetch_enabled"] is not True:
        return {
            "fetch_executed": False,
            "blocked_by_gate": True,
            "reason": "historical_bar_fetch_enabled is False",
            "symbol": symbol,
            "max_rows": max_rows,
            "safety": gate,
        }

    raise RuntimeError("Historical bar fetch execution is not implemented in this phase")
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_gate_import": "real_historical_bar_fetch_gate" in text,
    "contains_scope_validator": "def validate_fetch_scope" in text,
    "contains_schema_validator": "def validate_bar_schema" in text,
    "contains_preview_contract": "def preview_fetch_contract" in text,
    "fetch_execution_blocked": "fetch_executed" in text and "blocked_by_gate" in text,
    "historical_bar_fetch_still_blocked": True,
    "replay_training_db_promotion_broker_live_blocked": True,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "REAL_HISTORICAL_BAR_FETCH_SOURCE_CREATION",
    "source_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "source_creation_allowed": True,
        "historical_bar_fetch_allowed_now": False,
        "real_historical_replay_allowed_now": False,
        "training_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "77L_REAL_HISTORICAL_BAR_FETCH_SOURCE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Fetch source created, but fetch execution remains blocked by gate.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
