#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "strategy_knowledge_extraction_plan/124A_strategy_knowledge_extraction_plan_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/strategy_knowledge_object.py"

OUT_DIR = ARCH / "strategy_knowledge_object_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "124B_strategy_knowledge_object_stub_latest.json"
OUT_TXT = OUT_DIR / "124B_strategy_knowledge_object_stub_latest.txt"

PHASE = "124B_STRATEGY_KNOWLEDGE_OBJECT_STUB"

SOURCE_TEXT = '''"""Strategy knowledge object.

Generated by 124B_STRATEGY_KNOWLEDGE_OBJECT_STUB.

Turns certified learning artifacts and research references into
read-only strategy knowledge objects.

No strategy execution.
No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

STRATEGY_KNOWLEDGE_OBJECT_KEYS = {
    "knowledge_id",
    "strategy_name",
    "strategy_family",
    "symbols",
    "asset_classes",
    "indicators",
    "regimes",
    "features",
    "evidence",
    "risk_notes",
    "source_artifacts",
    "confidence",
    "safety_locks",
    "created_at",
}

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
}

def knowledge_object_status() -> dict[str, Any]:
    return {
        "strategy_knowledge_object_enabled": True,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }

def build_strategy_knowledge_object(
    *,
    strategy_name: str,
    strategy_family: str = "UNCLASSIFIED",
    symbols: list[str] | None = None,
    asset_classes: list[str] | None = None,
    indicators: list[str] | None = None,
    regimes: list[str] | None = None,
    features: dict[str, Any] | None = None,
    evidence: list[dict[str, Any]] | None = None,
    risk_notes: list[str] | None = None,
    source_artifacts: list[dict[str, Any]] | None = None,
    confidence: float = 0.0,
) -> dict[str, Any]:
    safe_confidence = max(0.0, min(1.0, float(confidence)))

    symbol_key = "_".join(sorted(symbols or ["GLOBAL"]))
    strategy_key = strategy_name.strip().replace(" ", "_").upper() or "UNKNOWN_STRATEGY"

    return {
        "knowledge_id": f"SKO:{strategy_key}:{symbol_key}",
        "strategy_name": strategy_name,
        "strategy_family": strategy_family,
        "symbols": symbols or [],
        "asset_classes": asset_classes or [],
        "indicators": indicators or [],
        "regimes": regimes or [],
        "features": features or {},
        "evidence": evidence or [],
        "risk_notes": risk_notes or [],
        "source_artifacts": source_artifacts or [],
        "confidence": safe_confidence,
        "safety_locks": dict(SAFETY_LOCKS),
        "created_at": datetime.now(UTC).isoformat(),
    }

def build_strategy_knowledge_object_from_learning_artifact(
    artifact: dict[str, Any],
    strategy_name: str = "Learning Artifact Strategy",
    strategy_family: str = "LEARNING_ARTIFACT",
) -> dict[str, Any]:
    symbol = artifact.get("symbol")
    source_artifact = {
        "artifact_id": artifact.get("artifact_id"),
        "run_id": artifact.get("run_id"),
        "symbol": artifact.get("symbol"),
        "date": artifact.get("date"),
        "decision": artifact.get("decision"),
        "reward": artifact.get("reward"),
        "confidence": artifact.get("confidence"),
    }

    evidence = [{
        "type": "learning_artifact",
        "reward": artifact.get("reward"),
        "confidence": artifact.get("confidence"),
        "decision": artifact.get("decision"),
        "date": artifact.get("date"),
    }]

    return build_strategy_knowledge_object(
        strategy_name=strategy_name,
        strategy_family=strategy_family,
        symbols=[symbol] if symbol else [],
        asset_classes=[],
        indicators=[],
        regimes=[],
        features=artifact.get("features") or {},
        evidence=evidence,
        risk_notes=[],
        source_artifacts=[source_artifact],
        confidence=float(artifact.get("confidence") or 0.0),
    )

def validate_strategy_knowledge_object(obj: dict[str, Any]) -> bool:
    if set(obj.keys()) != STRATEGY_KNOWLEDGE_OBJECT_KEYS:
        return False

    if not obj.get("knowledge_id"):
        return False

    if not obj.get("strategy_name"):
        return False

    if not isinstance(obj.get("symbols"), list):
        return False

    if not isinstance(obj.get("asset_classes"), list):
        return False

    if not isinstance(obj.get("indicators"), list):
        return False

    if not isinstance(obj.get("regimes"), list):
        return False

    if not isinstance(obj.get("features"), dict):
        return False

    if not isinstance(obj.get("evidence"), list):
        return False

    confidence = obj.get("confidence")
    if not isinstance(confidence, (int, float)):
        return False

    if not (0.0 <= float(confidence) <= 1.0):
        return False

    locks = obj.get("safety_locks", {})
    return (
        locks.get("database_writes_allowed") is False
        and locks.get("strategy_db_write_allowed") is False
        and locks.get("promotion_enabled") is False
        and locks.get("broker_execution_enabled") is False
        and locks.get("live_execution_enabled") is False
    )
'''

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "keys_present": "STRATEGY_KNOWLEDGE_OBJECT_KEYS" in text,
    "status_present": "def knowledge_object_status" in text,
    "builder_present": "def build_strategy_knowledge_object" in text,
    "artifact_builder_present": "def build_strategy_knowledge_object_from_learning_artifact" in text,
    "validator_present": "def validate_strategy_knowledge_object" in text,
    "db_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "strategy_knowledge_object_created": True,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "124C_STRATEGY_KNOWLEDGE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        f"target_file: {TARGET}",
        "",
        "Strategy knowledge object stub created.",
        "No DB writes. No promotion. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
