#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "patch_manifest_rollup" / "66G_replay_runtime_patch_manifest_rollup_latest.json"
MANIFEST = ARCH / "patch_manifest_preview" / "66F_replay_runtime_source_patch_manifest_preview_latest.json"

OUT_DIR = ARCH / "source_creation"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "67A_replay_contract_source_creation_latest.json"
OUT_TXT = OUT_DIR / "67A_replay_contract_source_creation_latest.txt"

PHASE = "67A_REPLAY_CONTRACT_SOURCE_CREATION"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


rollup = read_json(SOURCE)
manifest_data = read_json(MANIFEST)
patch_manifest = manifest_data.get("patch_manifest", [])

created = []

STUB = '''"""Read-only replay contract stub.

Generated by 67A_REPLAY_CONTRACT_SOURCE_CREATION.

This file defines contract shape only.
It must not execute replay, mutate runtime, write strategy DB,
promote candidates, place broker orders, or enable live trading.
"""

REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def contract_status() -> dict:
    return {
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
'''

for item in patch_manifest:
    target = ROOT / item["target_path"]
    target.parent.mkdir(parents=True, exist_ok=True)

    existed_before = target.exists()

    if not target.exists():
        target.write_text(STUB, encoding="utf-8")

    created.append({
        "path": item["target_path"],
        "existed_before": existed_before,
        "exists_after": target.exists(),
        "created_now": not existed_before and target.exists(),
        "contract_only": True,
    })

checks = {
    "rollup_exists": SOURCE.exists(),
    "rollup_certified": rollup.get("certified") is True,
    "manifest_exists": MANIFEST.exists(),
    "manifest_certified": manifest_data.get("certified") is True,
    "files_present": len(created) > 0,
    "all_exist_after": all(x["exists_after"] for x in created),
    "all_contract_only": all(x["contract_only"] is True for x in created),
    "historical_replay_blocked": True,
    "runtime_execution_blocked": True,
    "strategy_db_write_blocked": True,
    "promotion_blocked": True,
    "broker_live_blocked": True,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "CONTRACT_SOURCE_CREATION_ONLY",
    "source_rollup": str(SOURCE),
    "source_manifest": str(MANIFEST),
    "created_files": created,
    "policy": {
        "source_creation_allowed": True,
        "contract_only": True,
        "historical_replay_allowed_now": False,
        "runtime_execution_allowed": False,
        "runtime_mutation_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "67B_REPLAY_CONTRACT_SOURCE_CREATION_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

lines = [
    PHASE,
    "",
    f"certified: {result['certified']}",
    f"files: {len(created)}",
    "",
    "Created / verified:",
    "",
]

for item in created:
    lines.append(
        f"- {item['path']} | existed_before={item['existed_before']} | created_now={item['created_now']}"
    )

OUT_TXT.write_text("\n".join(lines), encoding="utf-8")

print(json.dumps({
    "phase": PHASE,
    "file_count": len(created),
    "certified": result["certified"],
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
