#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "learning_training_architecture" / "74A_learning_training_architecture_planning_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L1_security_auth_safety/training_enablement_gate.py"

OUT_DIR = ARCH / "training_gate_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "75A_training_gate_stub_latest.json"
OUT_TXT = OUT_DIR / "75A_training_gate_stub_latest.txt"

PHASE = "75A_TRAINING_GATE_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Training enablement gate.

Generated by 75A_TRAINING_GATE_STUB.

Training is explicitly disabled.
This gate must not enable learning, mutation, promotion,
strategy DB writes, broker execution, or live trading.
"""

TRAINING_ENABLED = False
SELF_MUTATION_ALLOWED = False
AUTONOMOUS_PROMOTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def training_gate_status() -> dict:
    return {
        "training_enabled": TRAINING_ENABLED,
        "self_mutation_allowed": SELF_MUTATION_ALLOWED,
        "autonomous_promotion_allowed": AUTONOMOUS_PROMOTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_training_gate_status": "def training_gate_status" in text,
    "training_disabled": "TRAINING_ENABLED = False" in text,
    "self_mutation_blocked": "SELF_MUTATION_ALLOWED = False" in text,
    "autonomous_promotion_blocked": "AUTONOMOUS_PROMOTION_ALLOWED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "TRAINING_GATE_STUB_CREATION",
    "source_training_architecture": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "training_gate_stub_created": True,
        "training_enabled": False,
        "self_mutation_allowed": False,
        "autonomous_promotion_allowed": False,
        "strategy_db_write_allowed": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "75B_TRAINING_GATE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Training remains blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
