#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()

ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "eight_hour_training_preflight/128A_eight_hour_training_preflight_latest.json"

TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/training_observability_contract.py"

OUT_DIR = ARCH / "training_observability_contract"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "128B_training_observability_contract_latest.json"
OUT_TXT  = OUT_DIR / "128B_training_observability_contract_latest.txt"

PHASE="128B_TRAINING_OBSERVABILITY_CONTRACT"

SOURCE_TEXT = '''"""
Training Observability Contract

Generated by 128B_TRAINING_OBSERVABILITY_CONTRACT

Read Only

Replay
Paper Trading
Future Live Analytics

No DB Writes
No Broker
No Promotion
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False

TRAINING_METRICS={

"replay_metadata":[
"replay_id",
"run_uuid",
"git_commit",
"training_profile",
"dataset_version",
"start_time",
"end_time",
"duration",
],

"dataset_health":[
"symbols_loaded",
"bars_loaded",
"missing_bars",
"duplicate_bars",
"bad_rows",
"skipped_rows",
],

"cycle_statistics":[
"cycle",
"processing_time_ms",
"bars_processed",
"features_generated",
"knowledge_generated",
],

"decision_ledger":[
"timestamp",
"cycle",
"symbol",
"decision",
"strategy",
"confidence",
"reward",
"risk_score",
"market_regime",
"reason",
],

"action_statistics":[
"buy_count",
"sell_count",
"hold_count",
"skip_count",
],

"strategy_statistics":[
"wins",
"losses",
"profit_factor",
"expectancy",
"sharpe",
"sortino",
"max_drawdown",
],

"indicator_statistics":[
"usage",
"accuracy",
"average_reward",
"best_symbol",
"best_regime",
],

"symbol_profiles":[
"average_reward",
"average_confidence",
"best_strategy",
"best_regime",
],

"market_regimes":[
"year",
"month",
"week",
"day",
"hour",
],

"equity_curve":[
"equity",
"drawdown",
"rolling_reward",
"rolling_win_rate",
"rolling_sharpe",
"rolling_sortino",
],

"confidence_calibration":[
"predicted_confidence",
"actual_accuracy",
"brier_score",
],

"knowledge_growth":[
"artifacts",
"knowledge_objects",
"graph_nodes",
"graph_edges",
"research_links",
],

"performance":[
"cpu_percent",
"ram_percent",
"bars_per_second",
"rows_per_second",
],

"training_health":[
"overall_score",
"learning_score",
"data_quality",
"risk_score",
],
}

def observability_status()->dict[str,Any]:

    return{

        "enabled":True,

        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }

def required_sections()->list[str]:
    return sorted(TRAINING_METRICS.keys())

def required_metrics(section:str)->list[str]:
    return TRAINING_METRICS.get(section,[])

def create_empty_report()->dict[str,Any]:

    report={

        "created_at":datetime.now(UTC).isoformat(),

        "status":observability_status(),

        "sections":{},
    }

    for section,metrics in TRAINING_METRICS.items():

        report["sections"][section]={

            metric:None

            for metric in metrics
        }

    return report
'''

def read_json(path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}

source=read_json(SOURCE)

TARGET.write_text(SOURCE_TEXT,encoding="utf-8")

compile_ok=False

try:
    py_compile.compile(str(TARGET),doraise=True)
    compile_ok=True
except Exception as exc:
    compile_error=str(exc)
else:
    compile_error=None

text=TARGET.read_text()

checks={

"source_exists":SOURCE.exists(),
"source_certified":source.get("certified") is True,

"target_exists":TARGET.exists(),

"compile_ok":compile_ok,

"status_present":"observability_status" in text,
"metrics_present":"TRAINING_METRICS" in text,
"report_builder_present":"create_empty_report" in text,

"db_blocked":"DATABASE_WRITES_ALLOWED=False" in text,
"broker_blocked":"BROKER_EXECUTION_ENABLED=False" in text,
"live_blocked":"LIVE_EXECUTION_ENABLED=False" in text,

}

result={

"phase":PHASE,
"created_at":datetime.now(UTC).isoformat(),

"checks":checks,

"compile_error":compile_error,

"recommended_next_phase":"128C_TRAINING_OBSERVABILITY_CERTIFICATION",

"certified":all(checks.values()),

}

OUT_JSON.write_text(json.dumps(result,indent=2),encoding="utf-8")

OUT_TXT.write_text(
"\n".join([
PHASE,
"",
f"certified: {result['certified']}",
f"compile_ok: {compile_ok}",
"",
"Observability Contract Created",
"",
"Replay Metadata",
"Dataset Health",
"Cycle Ledger",
"Decision Ledger",
"Strategy Statistics",
"Indicator Statistics",
"Equity Curve",
"Confidence Calibration",
"Knowledge Growth",
"Performance",
"Training Health",
"",
"Broker Disabled",
"Database Disabled",
"Promotion Disabled",
"",
"Next:",
result["recommended_next_phase"],
]),
encoding="utf-8",
)

print(json.dumps({

"phase":PHASE,
"certified":result["certified"],
"compile_ok":compile_ok,
"recommended_next_phase":result["recommended_next_phase"],
"out_json":str(OUT_JSON),
"out_txt":str(OUT_TXT),

},indent=2))
