#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json, py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "research_repository_training_manifest_refresh/119A_research_repository_training_manifest_refresh_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/repository_replay_input_wire.py"

OUT_DIR = ARCH / "replay_engine_repository_input_wire"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "119B_replay_engine_repository_input_wire_latest.json"
OUT_TXT = OUT_DIR / "119B_replay_engine_repository_input_wire_latest.txt"

PHASE = "119B_REPLAY_ENGINE_REPOSITORY_INPUT_WIRE"

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)
training_manifest_path = source.get("training_manifest")

SOURCE_TEXT = f'''"""Repository replay input wire.

Generated by 119B_REPLAY_ENGINE_REPOSITORY_INPUT_WIRE.

This wires the replay engine to the approved research repository manifest.
It does not execute training.
It does not write to DB.
It does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
import json

REPOSITORY_TRAINING_MANIFEST = Path({training_manifest_path!r})

REPLAY_REPOSITORY_INPUT_ENABLED = True
TRAINING_EXECUTION_ENABLED = False
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def wire_status() -> dict:
    return {{
        "repository_training_manifest": str(REPOSITORY_TRAINING_MANIFEST),
        "replay_repository_input_enabled": REPLAY_REPOSITORY_INPUT_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }}


def load_repository_training_manifest() -> dict:
    return json.loads(REPOSITORY_TRAINING_MANIFEST.read_text(encoding="utf-8"))


def preview_repository_replay_inputs() -> dict:
    manifest = load_repository_training_manifest()
    return {{
        "mode": "REPOSITORY_REPLAY_INPUT_PREVIEW",
        "approved_for_training": manifest.get("approved_for_training"),
        "csv_file_count": manifest.get("csv_file_count"),
        "excluded_row_count": manifest.get("excluded_row_count"),
        "training_executed": False,
        "status": wire_status(),
    }}
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None
try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "manifest_path_present": bool(training_manifest_path),
    "repository_input_enabled": "REPLAY_REPOSITORY_INPUT_ENABLED = True" in text,
    "training_still_disabled": "TRAINING_EXECUTION_ENABLED = False" in text,
    "db_write_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "training_manifest": training_manifest_path,
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "replay_repository_input_enabled": True,
        "training_execution_enabled": False,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "119C_ONE_HOUR_REPOSITORY_REPLAY_VALIDATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "replay_repository_input_enabled: True",
        "training_execution_enabled: False",
        "",
        "Replay engine wired to repository input manifest.",
        "No replay executed. No DB writes. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
