#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "long_training_run_enablement_preview/120A_long_training_run_enablement_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/long_training_run_executor.py"

OUT_DIR = ARCH / "long_training_run_executor_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "120B_long_training_run_executor_stub_latest.json"
OUT_TXT = OUT_DIR / "120B_long_training_run_executor_stub_latest.txt"

PHASE = "120B_LONG_TRAINING_RUN_EXECUTOR_STUB"

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)

SOURCE_TEXT = '''"""Long training run executor stub.

Generated by 120B_LONG_TRAINING_RUN_EXECUTOR_STUB.

Defines the 8-hour training executor contract only.
Does not run training yet.
Does not write DB records.
Does not promote strategies.
Does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, UTC
import json

LONG_TRAINING_EXECUTOR_ENABLED = True
TRAINING_EXECUTION_ENABLED = False
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

DEFAULT_DURATION_SECONDS = 28800
DEFAULT_HEARTBEAT_SECONDS = 30
DEFAULT_CHECKPOINT_SECONDS = 300


def executor_status() -> dict:
    return {
        "long_training_executor_enabled": LONG_TRAINING_EXECUTOR_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "default_duration_seconds": DEFAULT_DURATION_SECONDS,
        "default_heartbeat_seconds": DEFAULT_HEARTBEAT_SECONDS,
        "default_checkpoint_seconds": DEFAULT_CHECKPOINT_SECONDS,
    }


def build_long_training_plan(
    run_id: str,
    repository_manifest: str,
    duration_seconds: int = DEFAULT_DURATION_SECONDS,
) -> dict:
    return {
        "run_id": run_id,
        "repository_manifest": repository_manifest,
        "duration_seconds": duration_seconds,
        "heartbeat_seconds": DEFAULT_HEARTBEAT_SECONDS,
        "checkpoint_seconds": DEFAULT_CHECKPOINT_SECONDS,
        "resume_supported": True,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "created_at": datetime.now(UTC).isoformat(),
    }


def write_heartbeat(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "timestamp": datetime.now(UTC).isoformat(),
        "payload": payload,
    }
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record))
        handle.write("\\n")


def write_checkpoint(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    checkpoint = {
        "timestamp": datetime.now(UTC).isoformat(),
        "payload": payload,
    }
    path.write_text(json.dumps(checkpoint, indent=2), encoding="utf-8")
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "executor_enabled": "LONG_TRAINING_EXECUTOR_ENABLED = True" in text,
    "training_still_disabled": "TRAINING_EXECUTION_ENABLED = False" in text,
    "duration_8h": "DEFAULT_DURATION_SECONDS = 28800" in text,
    "heartbeat_30s": "DEFAULT_HEARTBEAT_SECONDS = 30" in text,
    "checkpoint_300s": "DEFAULT_CHECKPOINT_SECONDS = 300" in text,
    "db_write_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "long_training_executor_stub_created": True,
        "long_training_executor_enabled": True,
        "training_execution_enabled": False,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "120C_LONG_TRAINING_RUN_EXECUTOR_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "duration_seconds: 28800",
        "heartbeat_seconds: 30",
        "checkpoint_seconds: 300",
        "training_execution_enabled: False",
        "",
        "Long training executor stub created.",
        "No training executed. No DB writes. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
