#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "market_regime_library_stub/127A_market_regime_library_stub_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/market_regime_classifier.py"

OUT_DIR = ARCH / "market_regime_classifier_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "127B_market_regime_classifier_stub_latest.json"
OUT_TXT = OUT_DIR / "127B_market_regime_classifier_stub_latest.txt"

PHASE = "127B_MARKET_REGIME_CLASSIFIER_STUB"

SOURCE_TEXT = '''"""Market Regime Classifier.

Generated by 127B_MARKET_REGIME_CLASSIFIER_STUB.

Read-only replay regime classifier.

No DB writes.
No strategy promotion.
No broker/live execution.
"""

from __future__ import annotations

from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False


def classifier_status()->dict[str,Any]:

    return{

        "enabled":True,

        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }


def classify_market_regime(

    *,
    daily_return:float|None,
    intraday_return:float|None,
    range_pct:float|None,

)->str:

    if daily_return is None:
        return "UNKNOWN"

    if range_pct is not None and range_pct>=0.05:
        return "HIGH_VOLATILITY"

    if daily_return>=0.01:
        return "BULLISH_MOMENTUM"

    if daily_return<=-0.01:
        return "BEARISH_TREND"

    return "SIDEWAYS_RANGE"


def classify_feature_set(

    features:dict[str,Any],

)->str:

    return classify_market_regime(

        daily_return=features.get("daily_return"),
        intraday_return=features.get("intraday_return"),
        range_pct=features.get("range_pct"),

    )
'''

def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source=read_json(SOURCE)

TARGET.write_text(SOURCE_TEXT,encoding="utf-8")

compile_ok=False
compile_error=None

try:
    py_compile.compile(str(TARGET),doraise=True)
    compile_ok=True
except Exception as exc:
    compile_error={
        "type":type(exc).__name__,
        "message":str(exc),
    }

text=TARGET.read_text(encoding="utf-8")

checks={

    "source_exists":SOURCE.exists(),
    "source_certified":source.get("certified") is True,

    "target_written":TARGET.exists(),

    "compile_ok":compile_ok,

    "status_present":"classifier_status" in text,
    "classifier_present":"classify_market_regime" in text,
    "feature_classifier_present":"classify_feature_set" in text,

    "db_blocked":"DATABASE_WRITES_ALLOWED=False" in text,

    "broker_blocked":"BROKER_EXECUTION_ENABLED=False" in text,

    "live_blocked":"LIVE_EXECUTION_ENABLED=False" in text,
}

result={

    "phase":PHASE,
    "created_at":datetime.now(UTC).isoformat(),

    "target_file":str(TARGET),

    "compile_error":compile_error,

    "checks":checks,

    "recommended_next_phase":
        "127C_MARKET_REGIME_CERTIFICATION",

    "certified":
        all(checks.values()),
}

OUT_JSON.write_text(
    json.dumps(result,indent=2),
    encoding="utf-8",
)

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "",
        "Market regime classifier created.",
        "Read only.",
        "No DB writes.",
        "No promotion.",
        "No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({

    "phase":PHASE,
    "certified":result["certified"],
    "compile_ok":compile_ok,
    "recommended_next_phase":
        result["recommended_next_phase"],
    "out_json":str(OUT_JSON),
    "out_txt":str(OUT_TXT),

},indent=2))
