#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "dev_territory_command_registry_preview" / "106A_dev_territory_command_registry_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/dev_territory_command_registry.py"

OUT_DIR = ARCH / "dev_territory_command_registry"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "106B_dev_territory_command_registry_stub_latest.json"
OUT_TXT = OUT_DIR / "106B_dev_territory_command_registry_stub_latest.txt"

PHASE = "106B_DEV_TERRITORY_COMMAND_REGISTRY_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)
commands = source.get("commands", [])
doctrine = source.get("doctrine", {})

SOURCE_TEXT = f'''"""Dev Territory Command Registry.

Generated by 106B_DEV_TERRITORY_COMMAND_REGISTRY_STUB.

This registry is sandbox-facing only.
It grants analytical capability only.
It never grants persistence, mutation, promotion, broker execution, or live trading.
"""

from __future__ import annotations

DEV_TERRITORY_REGISTRY_ENABLED = False
REGISTRY_WRITE_TO_RUNTIME_ENABLED = False
TRAINING_EXECUTION_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

COMMANDS = {json.dumps(commands, indent=4)}

DOCTRINE = {json.dumps(doctrine, indent=4)}


def registry_status() -> dict:
    return {{
        "dev_territory_registry_enabled": DEV_TERRITORY_REGISTRY_ENABLED,
        "registry_write_to_runtime_enabled": REGISTRY_WRITE_TO_RUNTIME_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "command_count": len(COMMANDS),
    }}


def list_dev_territory_commands() -> list[dict]:
    return COMMANDS


def get_dev_territory_doctrine() -> dict:
    return DOCTRINE
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "commands_loaded": len(commands) == 7,
    "contains_status": "def registry_status" in text,
    "contains_list_commands": "def list_dev_territory_commands" in text,
    "contains_doctrine": "def get_dev_territory_doctrine" in text,
    "registry_disabled": "DEV_TERRITORY_REGISTRY_ENABLED = False" in text,
    "runtime_write_blocked": "REGISTRY_WRITE_TO_RUNTIME_ENABLED = False" in text,
    "training_blocked": "TRAINING_EXECUTION_ENABLED = False" in text,
    "learner_write_blocked": "LEARNER_WRITE_ENABLED = False" in text,
    "mutation_blocked": "MUTATION_ALLOWED = False" in text,
    "queue_write_blocked": "QUEUE_WRITE_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "DEV_TERRITORY_COMMAND_REGISTRY_STUB",
    "source_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "dev_territory_registry_stub_created": True,
        "dev_territory_registry_enabled": False,
        "registry_write_to_runtime_enabled": False,
        "training_execution_enabled": False,
        "learner_write_enabled": False,
        "mutation_allowed": False,
        "queue_write_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "106C_DEV_TERRITORY_COMMAND_REGISTRY_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        f"commands: {len(commands)}",
        "",
        "Dev territory registry stub created.",
        "Registry/runtime/training/db/mutation/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "commands": len(commands),
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
