#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()

TARGET = ROOT / "backend/app/stacks/strategy/signal.py"

OUT_DIR = ROOT / "runtime/replay_runtime_architecture/multi_indicator_strategy_engine"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "130A_multi_indicator_strategy_engine_latest.json"
OUT_TXT = OUT_DIR / "130A_multi_indicator_strategy_engine_latest.txt"

PHASE = "130A_MULTI_INDICATOR_STRATEGY_ENGINE"

SOURCE_TEXT = '''"""Multi-indicator strategy signal generation.

Generated by 130A_MULTI_INDICATOR_STRATEGY_ENGINE.

Replay-safe.
Uses provided bars.
Does not fetch live data.
Does not execute broker actions.
"""

from __future__ import annotations

import numpy as np


def _close_series(bars: list[dict]) -> list[float]:
    return [float(bar["close"]) for bar in bars if "close" in bar and bar["close"] not in (None, "")]


def _volume_series(bars: list[dict]) -> list[float]:
    return [float(bar.get("volume", 0.0) or 0.0) for bar in bars]


def _ema(values: list[float], period: int) -> float | None:
    if len(values) < period:
        return None

    alpha = 2 / (period + 1)
    ema = values[-period]

    for value in values[-period + 1:]:
        ema = alpha * value + (1 - alpha) * ema

    return float(ema)


def _rsi(values: list[float], period: int = 14) -> float | None:
    if len(values) < period + 1:
        return None

    window = values[-(period + 1):]
    diffs = np.diff(window)

    gains = np.where(diffs > 0, diffs, 0.0)
    losses = np.where(diffs < 0, -diffs, 0.0)

    avg_gain = float(np.mean(gains))
    avg_loss = float(np.mean(losses))

    if avg_loss == 0:
        return 100.0

    if avg_gain == 0:
        return 0.0

    rs = avg_gain / avg_loss
    return float(100.0 - (100.0 / (1.0 + rs)))


def _macd(values: list[float]) -> dict:
    ema12 = _ema(values, 12)
    ema26 = _ema(values, 26)

    if ema12 is None or ema26 is None:
        return {"macd": None, "bias": "neutral"}

    macd = ema12 - ema26

    if macd > 0:
        bias = "bullish"
    elif macd < 0:
        bias = "bearish"
    else:
        bias = "neutral"

    return {"macd": float(macd), "bias": bias}


def _bollinger(values: list[float], period: int = 20) -> dict:
    if len(values) < period:
        return {"position": None, "bias": "neutral"}

    window = np.array(values[-period:], dtype=float)
    mean = float(np.mean(window))
    std = float(np.std(window))

    if std == 0:
        return {"position": 0.5, "bias": "neutral"}

    close = float(values[-1])
    upper = mean + (2 * std)
    lower = mean - (2 * std)

    position = (close - lower) / max(upper - lower, 1e-9)

    if position <= 0.2:
        bias = "oversold"
    elif position >= 0.8:
        bias = "overbought"
    else:
        bias = "neutral"

    return {
        "position": float(position),
        "upper": upper,
        "lower": lower,
        "middle": mean,
        "bias": bias,
    }


def _volume_spike(bars: list[dict], period: int = 20) -> dict:
    volumes = _volume_series(bars)

    if len(volumes) < period + 1:
        return {"ratio": 1.0, "spike": False}

    current = volumes[-1]
    avg = float(np.mean(volumes[-period - 1:-1]))

    if avg <= 0:
        return {"ratio": 1.0, "spike": False}

    ratio = current / avg

    return {
        "ratio": float(ratio),
        "spike": bool(ratio >= 1.5),
    }


def generate_signal(symbol: str, latest_price: dict, bars: list[dict], lookback_period: int = 14) -> dict:
    closes = _close_series(bars)

    if len(closes) < 30:
        return {
            "status": "no_action",
            "action": "hold",
            "decision": "HOLD",
            "symbol": symbol,
            "reason": "not_enough_bars",
            "bar_count": len(closes),
        }

    rsi = _rsi(closes, lookback_period)
    macd = _macd(closes)
    bb = _bollinger(closes)
    vol = _volume_spike(bars)

    ema_fast = _ema(closes, 10)
    ema_slow = _ema(closes, 30)

    score = 0
    reasons = []

    if rsi is not None:
        if rsi <= 45:
            score += 1
            reasons.append("RSI bullish/discount")
        elif rsi >= 55:
            score -= 1
            reasons.append("RSI bearish/extended")

    if macd["bias"] == "bullish":
        score += 1
        reasons.append("MACD bullish")
    elif macd["bias"] == "bearish":
        score -= 1
        reasons.append("MACD bearish")

    if bb["bias"] == "oversold":
        score += 1
        reasons.append("Bollinger oversold")
    elif bb["bias"] == "overbought":
        score -= 1
        reasons.append("Bollinger overbought")

    if ema_fast is not None and ema_slow is not None:
        if ema_fast > ema_slow:
            score += 1
            reasons.append("EMA fast above slow")
        elif ema_fast < ema_slow:
            score -= 1
            reasons.append("EMA fast below slow")

    if vol["spike"]:
        reasons.append("Volume spike confirmed")

    if score >= 2:
        action = "buy"
    elif score <= -2:
        action = "sell"
    else:
        action = "hold"

    confidence = min(1.0, abs(score) / 4.0)

    return {
        "status": "ok",
        "symbol": symbol,
        "action": action,
        "decision": action.upper(),
        "score": score,
        "confidence": round(confidence, 3),
        "indicators": {
            "rsi": round(rsi, 2) if rsi is not None else None,
            "macd": macd,
            "bollinger": bb,
            "ema_fast": ema_fast,
            "ema_slow": ema_slow,
            "volume": vol,
        },
        "reasons": reasons,
    }
'''

TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = str(exc)

text = TARGET.read_text(encoding="utf-8")

checks = {
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "rsi_present": "def _rsi" in text,
    "macd_present": "def _macd" in text,
    "bollinger_present": "def _bollinger" in text,
    "ema_present": "def _ema" in text,
    "volume_present": "def _volume_spike" in text,
    "generate_signal_present": "def generate_signal" in text,
    "no_yfinance_import": "yfinance" not in text,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "recommended_next_phase": "130B_MULTI_INDICATOR_REPLAY_TEST",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "",
        "Indicators:",
        "- RSI",
        "- MACD",
        "- Bollinger Bands",
        "- EMA 10/30",
        "- Volume spike",
        "",
        "Replay-safe strategy signal engine installed.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
