#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "fixture_bar_math_function_preview" / "69A_fixture_bar_math_function_stub_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L2_domain/bar_replay_math_contract.py"

OUT_DIR = ARCH / "fixture_bar_math_function_source"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "69B_fixture_bar_math_function_source_creation_latest.json"
OUT_TXT = OUT_DIR / "69B_fixture_bar_math_function_source_creation_latest.txt"

PHASE = "69B_FIXTURE_BAR_MATH_FUNCTION_SOURCE_CREATION"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Fixture bar math contract functions.

Generated by 69B_FIXTURE_BAR_MATH_FUNCTION_SOURCE_CREATION.

These functions are pure math helpers only.
They do not run replay, score strategies, write strategy DB,
promote candidates, place broker orders, or enable live trading.
"""

from __future__ import annotations

from math import sqrt


REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def contract_status() -> dict:
    return {
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def calculate_simple_returns(close_prices: list[float]) -> list[float]:
    if len(close_prices) < 2:
        return []

    returns: list[float] = []
    for previous, current in zip(close_prices, close_prices[1:]):
        if previous == 0:
            returns.append(0.0)
        else:
            returns.append((current / previous) - 1.0)

    return returns


def calculate_cumulative_return(returns: list[float]) -> float:
    total = 1.0

    for value in returns:
        total *= 1.0 + value

    return total - 1.0


def calculate_rolling_mean(values: list[float], window: int) -> list[float | None]:
    if window <= 0:
        raise ValueError("window must be greater than zero")

    output: list[float | None] = []

    for index in range(len(values)):
        if index + 1 < window:
            output.append(None)
            continue

        section = values[index + 1 - window:index + 1]
        output.append(sum(section) / window)

    return output


def calculate_rolling_volatility(returns: list[float], window: int) -> list[float | None]:
    if window <= 0:
        raise ValueError("window must be greater than zero")

    output: list[float | None] = []

    for index in range(len(returns)):
        if index + 1 < window:
            output.append(None)
            continue

        section = returns[index + 1 - window:index + 1]
        mean = sum(section) / window
        variance = sum((value - mean) ** 2 for value in section) / window
        output.append(sqrt(variance))

    return output


def calculate_max_drawdown(equity_curve: list[float]) -> float:
    if not equity_curve:
        return 0.0

    peak = equity_curve[0]
    max_drawdown = 0.0

    for value in equity_curve:
        peak = max(peak, value)

        if peak == 0:
            drawdown = 0.0
        else:
            drawdown = (value / peak) - 1.0

        max_drawdown = min(max_drawdown, drawdown)

    return max_drawdown


def calculate_trade_count_proxy(signal_states: list[int]) -> int:
    if len(signal_states) < 2:
        return 0

    count = 0

    for previous, current in zip(signal_states, signal_states[1:]):
        if previous != current:
            count += 1

    return count
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {
        "type": type(exc).__name__,
        "message": str(exc),
    }

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_contract_status": "def contract_status" in TARGET.read_text(encoding="utf-8"),
    "contains_all_functions": all(
        name in TARGET.read_text(encoding="utf-8")
        for name in [
            "calculate_simple_returns",
            "calculate_cumulative_return",
            "calculate_rolling_mean",
            "calculate_rolling_volatility",
            "calculate_max_drawdown",
            "calculate_trade_count_proxy",
        ]
    ),
    "historical_replay_blocked": True,
    "runtime_execution_blocked": True,
    "strategy_db_write_blocked": True,
    "promotion_blocked": True,
    "broker_live_blocked": True,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "FIXTURE_BAR_MATH_FUNCTION_SOURCE_CREATION",
    "source_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "source_write_allowed_for_contract_math_file": True,
        "math_helpers_allowed": True,
        "historical_replay_allowed_now": False,
        "runtime_execution_allowed": False,
        "runtime_mutation_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "69C_FIXTURE_BAR_MATH_FUNCTION_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
