#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "symbol_intelligence_profile_certification/126B_symbol_intelligence_profile_certification_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/market_regime_library.py"

OUT_DIR = ARCH / "market_regime_library_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "127A_market_regime_library_stub_latest.json"
OUT_TXT = OUT_DIR / "127A_market_regime_library_stub_latest.txt"

PHASE = "127A_MARKET_REGIME_LIBRARY_STUB"

SOURCE_TEXT = '''"""Market Regime Library.

Generated by 127A_MARKET_REGIME_LIBRARY_STUB.

Read-only regime definitions used by replay learning.

No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False

SAFETY_LOCKS={
    "database_writes_allowed":False,
    "strategy_db_write_allowed":False,
    "promotion_enabled":False,
    "broker_execution_enabled":False,
    "live_execution_enabled":False,
}

REGIME_LIBRARY={

    "BULLISH_MOMENTUM":{
        "trend":"UP",
        "volatility":"NORMAL",
        "risk":"MEDIUM",
    },

    "BEARISH_TREND":{
        "trend":"DOWN",
        "volatility":"NORMAL",
        "risk":"HIGH",
    },

    "SIDEWAYS_RANGE":{
        "trend":"FLAT",
        "volatility":"LOW",
        "risk":"LOW",
    },

    "HIGH_VOLATILITY":{
        "trend":"ANY",
        "volatility":"HIGH",
        "risk":"HIGH",
    },

    "LOW_VOLATILITY":{
        "trend":"ANY",
        "volatility":"LOW",
        "risk":"LOW",
    },
}

def regime_library_status()->dict[str,Any]:

    return{
        "enabled":True,
        "regimes":sorted(REGIME_LIBRARY.keys()),
        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }

def get_market_regime(name:str)->dict[str,Any]|None:
    return REGIME_LIBRARY.get(str(name).upper())

def list_market_regimes()->list[str]:
    return sorted(REGIME_LIBRARY.keys())
'''

def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source=read_json(SOURCE)

TARGET.write_text(SOURCE_TEXT,encoding="utf-8")

compile_ok=False
compile_error=None

try:
    py_compile.compile(str(TARGET),doraise=True)
    compile_ok=True
except Exception as exc:
    compile_error={
        "type":type(exc).__name__,
        "message":str(exc),
    }

text=TARGET.read_text(encoding="utf-8")

checks={
    "source_exists":SOURCE.exists(),
    "source_certified":source.get("certified") is True,
    "target_written":TARGET.exists(),
    "compile_ok":compile_ok,
    "status_present":"regime_library_status" in text,
    "lookup_present":"get_market_regime" in text,
    "list_present":"list_market_regimes" in text,
    "library_present":"REGIME_LIBRARY" in text,
    "db_blocked":"DATABASE_WRITES_ALLOWED=False" in text,
    "broker_blocked":"BROKER_EXECUTION_ENABLED=False" in text,
    "live_blocked":"LIVE_EXECUTION_ENABLED=False" in text,
}

result={
    "phase":PHASE,
    "created_at":datetime.now(UTC).isoformat(),
    "target_file":str(TARGET),
    "compile_error":compile_error,
    "checks":checks,
    "recommended_next_phase":"127B_MARKET_REGIME_CLASSIFIER_STUB",
    "certified":all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result,indent=2),encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "",
        "Market regime library created.",
        "Read only.",
        "No DB writes.",
        "No promotion.",
        "No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase":PHASE,
    "certified":result["certified"],
    "compile_ok":compile_ok,
    "recommended_next_phase":result["recommended_next_phase"],
    "out_json":str(OUT_JSON),
    "out_txt":str(OUT_TXT),
},indent=2))
