#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "real_historical_bar_source_fetch_preview" / "77F_real_historical_bar_source_fetch_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L1_security_auth_safety/real_historical_bar_fetch_gate.py"

OUT_DIR = ARCH / "real_historical_bar_source_fetch_gate"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "77G_real_historical_bar_source_fetch_gate_latest.json"
OUT_TXT = OUT_DIR / "77G_real_historical_bar_source_fetch_gate_latest.txt"

PHASE = "77G_REAL_HISTORICAL_BAR_SOURCE_FETCH_GATE"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Real historical bar fetch gate.

Generated by 77G_REAL_HISTORICAL_BAR_SOURCE_FETCH_GATE.

Historical bar fetch is still disabled by default.
This gate only defines the future safe fetch boundary.
"""

HISTORICAL_BAR_FETCH_ENABLED = False
REAL_HISTORICAL_REPLAY_ENABLED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

MAX_SYMBOLS_ALLOWED = 1
MAX_ROWS_ALLOWED = 300
SYMBOL_ALLOWLIST = ["VFV.TO"]


def historical_bar_fetch_gate_status() -> dict:
    return {
        "historical_bar_fetch_enabled": HISTORICAL_BAR_FETCH_ENABLED,
        "real_historical_replay_enabled": REAL_HISTORICAL_REPLAY_ENABLED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "max_symbols_allowed": MAX_SYMBOLS_ALLOWED,
        "max_rows_allowed": MAX_ROWS_ALLOWED,
        "symbol_allowlist": SYMBOL_ALLOWLIST,
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_gate_status": "def historical_bar_fetch_gate_status" in text,
    "historical_bar_fetch_disabled": "HISTORICAL_BAR_FETCH_ENABLED = False" in text,
    "real_historical_replay_disabled": "REAL_HISTORICAL_REPLAY_ENABLED = False" in text,
    "training_disabled": "TRAINING_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
    "scope_limited": (
        "MAX_SYMBOLS_ALLOWED = 1" in text
        and "MAX_ROWS_ALLOWED = 300" in text
        and 'SYMBOL_ALLOWLIST = ["VFV.TO"]' in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "REAL_HISTORICAL_BAR_SOURCE_FETCH_GATE",
    "source_fetch_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "historical_bar_fetch_gate_created": True,
        "historical_bar_fetch_enabled": False,
        "real_historical_replay_enabled": False,
        "training_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "77H_REAL_HISTORICAL_BAR_SOURCE_FETCH_GATE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Historical bar fetch remains blocked.",
        "Replay/training/db/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
