#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "near_miss_refactor_queue_rollup" / "80C_near_miss_refactor_queue_rollup_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/candidate_quarantine_trash_path.py"

OUT_DIR = ARCH / "candidate_quarantine_trash_path"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "81A_candidate_quarantine_trash_path_latest.json"
OUT_TXT = OUT_DIR / "81A_candidate_quarantine_trash_path_latest.txt"

PHASE = "81A_CANDIDATE_QUARANTINE_TRASH_PATH"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Candidate quarantine / trash path.

Generated by 81A_CANDIDATE_QUARANTINE_TRASH_PATH.

This is contract-only.
No deletion, no mutation, no training, no strategy DB writes,
no promotion, no broker execution, no live trading.
"""

from __future__ import annotations


QUARANTINE_PATH_ENABLED = False
TRASH_PATH_ENABLED = False
DELETE_ALLOWED = False
MUTATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

QUARANTINE_ROOT = "runtime/replay_runtime_architecture/candidate_quarantine/"
TRASH_ROOT = "runtime/replay_runtime_architecture/candidate_trash/"


def quarantine_trash_status() -> dict:
    return {
        "quarantine_path_enabled": QUARANTINE_PATH_ENABLED,
        "trash_path_enabled": TRASH_PATH_ENABLED,
        "delete_allowed": DELETE_ALLOWED,
        "mutation_allowed": MUTATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "quarantine_root": QUARANTINE_ROOT,
        "trash_root": TRASH_ROOT,
    }


def preview_quarantine_record(candidate_id: str, reason: str) -> dict:
    return {
        "mode": "PREVIEW_ONLY",
        "candidate_id": candidate_id,
        "reason": reason,
        "quarantine_allowed_now": QUARANTINE_PATH_ENABLED,
        "trash_allowed_now": TRASH_PATH_ENABLED,
        "delete_allowed_now": DELETE_ALLOWED,
        "status": quarantine_trash_status(),
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_status": "def quarantine_trash_status" in text,
    "contains_preview": "def preview_quarantine_record" in text,
    "quarantine_disabled": "QUARANTINE_PATH_ENABLED = False" in text,
    "trash_disabled": "TRASH_PATH_ENABLED = False" in text,
    "delete_blocked": "DELETE_ALLOWED = False" in text,
    "mutation_blocked": "MUTATION_ALLOWED = False" in text,
    "training_blocked": "TRAINING_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "CANDIDATE_QUARANTINE_TRASH_PATH_STUB",
    "source_near_miss_rollup": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "candidate_quarantine_trash_path_stub_created": True,
        "quarantine_path_enabled": False,
        "trash_path_enabled": False,
        "delete_allowed": False,
        "mutation_allowed": False,
        "training_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "81B_CANDIDATE_QUARANTINE_TRASH_PATH_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Quarantine/trash path stub created.",
        "Quarantine/trash/delete/mutation/training/db/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
