#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "fixture_replay_calculator_preview" / "70A_fixture_replay_calculator_dry_run_preview_latest.json"

TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/fixture_replay_calculator.py"
MATH_IMPORT = "backend.app.stacks.strategy_candidate_sandbox.L2_domain.bar_replay_math_contract"

OUT_DIR = ARCH / "fixture_replay_calculator_source"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "70B_fixture_replay_calculator_source_creation_latest.json"
OUT_TXT = OUT_DIR / "70B_fixture_replay_calculator_source_creation_latest.txt"

PHASE = "70B_FIXTURE_REPLAY_CALCULATOR_SOURCE_CREATION"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = f'''"""Fixture replay calculator facade.

Generated by 70B_FIXTURE_REPLAY_CALCULATOR_SOURCE_CREATION.

This is a fixture-only calculator facade.
It may calculate fixture metrics, but it must not run strategy replay,
write strategy DB, promote candidates, place broker orders, or enable live trading.
"""

from __future__ import annotations

import csv
from pathlib import Path

from {MATH_IMPORT} import (
    calculate_simple_returns,
    calculate_cumulative_return,
    calculate_rolling_mean,
    calculate_rolling_volatility,
    calculate_max_drawdown,
    calculate_trade_count_proxy,
    contract_status,
)


REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def facade_status() -> dict:
    return {{
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "math_contract": contract_status(),
    }}


def load_fixture_bars(csv_path: str | Path) -> list[dict]:
    path = Path(csv_path)

    with path.open("r", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    return rows


def extract_close_prices(rows: list[dict]) -> list[float]:
    return [float(row["close"]) for row in rows]


def build_equity_curve_from_returns(returns: list[float], starting_equity: float = 1.0) -> list[float]:
    equity = starting_equity
    curve = [equity]

    for value in returns:
        equity *= 1.0 + value
        curve.append(equity)

    return curve


def calculate_fixture_metrics(csv_path: str | Path) -> dict:
    rows = load_fixture_bars(csv_path)
    closes = extract_close_prices(rows)

    returns = calculate_simple_returns(closes)
    equity_curve = build_equity_curve_from_returns(returns)

    signal_states = [1 if idx > 0 else 0 for idx, _ in enumerate(closes)]

    return {{
        "dataset_id": "fixture_ohlcv_v1",
        "row_count": len(rows),
        "simple_returns": returns,
        "cumulative_return": calculate_cumulative_return(returns),
        "rolling_mean_3": calculate_rolling_mean(closes, 3),
        "rolling_volatility_3": calculate_rolling_volatility(returns, 3),
        "max_drawdown": calculate_max_drawdown(equity_curve),
        "trade_count_proxy": calculate_trade_count_proxy(signal_states),
        "safety": facade_status(),
    }}
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {
        "type": type(exc).__name__,
        "message": str(exc),
    }

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_facade_status": "def facade_status" in text,
    "contains_calculate_fixture_metrics": "def calculate_fixture_metrics" in text,
    "contains_required_locks": all(flag in text for flag in [
        "REPLAY_RUNTIME_ENABLED = False",
        "HISTORICAL_REPLAY_ALLOWED = False",
        "STRATEGY_EXECUTION_ALLOWED = False",
        "STRATEGY_DB_WRITE_ALLOWED = False",
        "PROMOTION_ENABLED = False",
        "BROKER_EXECUTION_ENABLED = False",
        "LIVE_EXECUTION_ENABLED = False",
    ]),
    "historical_replay_blocked": True,
    "runtime_execution_blocked": True,
    "strategy_db_write_blocked": True,
    "promotion_blocked": True,
    "broker_live_blocked": True,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "FIXTURE_REPLAY_CALCULATOR_SOURCE_CREATION",
    "source_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "fixture_calculator_source_creation_allowed": True,
        "fixture_metric_calculation_allowed_future": True,
        "historical_replay_allowed_now": False,
        "strategy_replay_allowed_now": False,
        "runtime_execution_allowed": False,
        "runtime_mutation_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "70C_FIXTURE_REPLAY_CALCULATOR_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
