#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "bulk_download_execution_plan/116E_bulk_download_execution_plan_latest.json"

TARGET = ROOT / "backend/app/stacks/learning_research/L3_service_facade/bulk_historical_data_downloader.py"

OUT_DIR = ARCH / "bulk_historical_data_downloader_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "117A_bulk_historical_data_downloader_stub_latest.json"
OUT_TXT = OUT_DIR / "117A_bulk_historical_data_downloader_stub_latest.txt"

PHASE = "117A_BULK_HISTORICAL_DATA_DOWNLOADER_STUB"

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)

SOURCE_TEXT = '''"""Bulk historical data downloader stub.

Generated by 117A_BULK_HISTORICAL_DATA_DOWNLOADER_STUB.

This module defines the downloader contract only.
It does not download data yet.
It does not write to DB.
It does not train.
It does not touch broker/live systems.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, UTC
import json

DOWNLOADS_ENABLED = False
FILE_REPOSITORY_WRITES_ENABLED = False
DATABASE_WRITES_ALLOWED = False
TRAINING_EXECUTION_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def downloader_status() -> dict:
    return {
        "downloads_enabled": DOWNLOADS_ENABLED,
        "file_repository_writes_enabled": FILE_REPOSITORY_WRITES_ENABLED,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def load_bulk_download_plan(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def preview_download_batches(plan: dict) -> dict:
    batches = plan.get("batches", [])
    return {
        "mode": "DOWNLOAD_PREVIEW_ONLY",
        "plan_id": plan.get("plan_id"),
        "provider": plan.get("provider"),
        "total_symbols": plan.get("total_symbols"),
        "batch_count": len(batches),
        "downloads_executed": False,
        "status": downloader_status(),
    }


def build_symbol_dataset_manifest(
    symbol: str,
    asset_group: str,
    provider: str,
    interval: str,
    period: str,
    output_file: str,
    checksum_sha256: str | None = None,
    rows: int | None = None,
    first_date: str | None = None,
    last_date: str | None = None,
) -> dict:
    return {
        "dataset_id": f"YFINANCE_{asset_group.upper()}_{symbol.replace('.', '_').replace('^', '').replace('=', '_').replace('-', '_')}",
        "provider": provider,
        "asset_group": asset_group,
        "symbol": symbol,
        "interval": interval,
        "period": period,
        "output_file": output_file,
        "checksum_sha256": checksum_sha256,
        "rows": rows,
        "first_date": first_date,
        "last_date": last_date,
        "approved": False,
        "read_only": True,
        "normalized": False,
        "training_enabled": False,
        "created_at": datetime.now(UTC).isoformat(),
        "updated_at": datetime.now(UTC).isoformat(),
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "downloads_disabled": "DOWNLOADS_ENABLED = False" in text,
    "file_writes_disabled": "FILE_REPOSITORY_WRITES_ENABLED = False" in text,
    "db_write_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "training_blocked": "TRAINING_EXECUTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
    "status_function_present": "def downloader_status" in text,
    "preview_function_present": "def preview_download_batches" in text,
    "manifest_builder_present": "def build_symbol_dataset_manifest" in text,
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "downloader_stub_created": True,
        "downloads_enabled": False,
        "file_repository_writes_enabled": False,
        "database_writes_allowed": False,
        "training_execution_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "117B_BULK_HISTORICAL_DATA_DOWNLOADER_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Bulk historical downloader stub created.",
        "Downloads/file writes/DB/training/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
