#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "dev_command_read_only_execution_preview" / "108A_dev_command_read_only_execution_preview_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/dev_command_read_only_executor.py"

OUT_DIR = ARCH / "dev_command_read_only_execution"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "108B_dev_command_read_only_execution_stub_latest.json"
OUT_TXT = OUT_DIR / "108B_dev_command_read_only_execution_stub_latest.txt"

PHASE = "108B_DEV_COMMAND_READ_ONLY_EXECUTION_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Dev command read-only executor.

Generated by 108B_DEV_COMMAND_READ_ONLY_EXECUTION_STUB.

Executor is read-only.
It may list command intent and doctrine only.
It cannot train, mutate, write DB records, promote candidates,
touch broker systems, or execute live trades.
"""

from __future__ import annotations

COMMAND_EXECUTION_ENABLED = False
READ_ONLY_PREVIEW_ENABLED = True
TRAINING_EXECUTION_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def executor_status() -> dict:
    return {
        "command_execution_enabled": COMMAND_EXECUTION_ENABLED,
        "read_only_preview_enabled": READ_ONLY_PREVIEW_ENABLED,
        "training_execution_enabled": TRAINING_EXECUTION_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def preview_dev_command(command_name: str) -> dict:
    return {
        "mode": "READ_ONLY_COMMAND_PREVIEW",
        "command_name": command_name,
        "executed": False,
        "allowed_now": ["read command registry", "read doctrine", "produce preview response"],
        "blocked_now": [
            "training execution",
            "learner writes",
            "mutation",
            "queue writes",
            "strategy DB writes",
            "promotion",
            "broker execution",
            "live execution",
        ],
        "status": executor_status(),
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None
try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_status": "def executor_status" in text,
    "contains_preview": "def preview_dev_command" in text,
    "command_execution_disabled": "COMMAND_EXECUTION_ENABLED = False" in text,
    "read_only_preview_enabled": "READ_ONLY_PREVIEW_ENABLED = True" in text,
    "training_blocked": "TRAINING_EXECUTION_ENABLED = False" in text,
    "learner_write_blocked": "LEARNER_WRITE_ENABLED = False" in text,
    "mutation_blocked": "MUTATION_ALLOWED = False" in text,
    "queue_write_blocked": "QUEUE_WRITE_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "DEV_COMMAND_READ_ONLY_EXECUTION_STUB",
    "source_preview": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "dev_command_read_only_executor_stub_created": True,
        "command_execution_enabled": False,
        "read_only_preview_enabled": True,
        "training_execution_enabled": False,
        "learner_write_enabled": False,
        "mutation_allowed": False,
        "queue_write_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "108C_DEV_COMMAND_READ_ONLY_EXECUTION_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Read-only dev command executor stub created.",
        "Training/db/mutation/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
