#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "learning_artifact_contract_replication_plan/121C_learning_artifact_contract_replication_plan_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_artifact_contract.py"

OUT_DIR = ARCH / "learning_artifact_contract_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "121D_learning_artifact_contract_stub_latest.json"
OUT_TXT = OUT_DIR / "121D_learning_artifact_contract_stub_latest.txt"

PHASE = "121D_LEARNING_ARTIFACT_CONTRACT_STUB"

SOURCE_TEXT = '''"""Learning artifact contract.

Generated by 121D_LEARNING_ARTIFACT_CONTRACT_STUB.

Defines the read-only learning artifact shape used by repository replay.
No DB writes.
No strategy promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
    "source_csv_modification_allowed": False,
}

LEARNING_ARTIFACT_CONTRACT_KEYS = {
    "artifact_id",
    "run_id",
    "symbol",
    "date",
    "cycle",
    "features",
    "decision",
    "reward",
    "confidence",
    "source",
    "safety_locks",
    "created_at",
}

VALID_DECISIONS = {"BUY", "SELL", "HOLD"}


def build_learning_artifact_contract(
    run_id: str,
    symbol: str,
    date: str,
    cycle: int,
    features: dict[str, Any],
    decision: str,
    reward: float | None = None,
    confidence: float | None = None,
    source: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "artifact_id": f"{run_id}:{symbol}:{date}:{cycle}",
        "run_id": run_id,
        "symbol": symbol,
        "date": date,
        "cycle": cycle,
        "features": features,
        "decision": decision,
        "reward": reward,
        "confidence": confidence,
        "source": source or {},
        "safety_locks": dict(SAFETY_LOCKS),
        "created_at": datetime.now(UTC).isoformat(),
    }


def validate_learning_artifact_contract(artifact: dict[str, Any]) -> bool:
    if set(artifact.keys()) != LEARNING_ARTIFACT_CONTRACT_KEYS:
        return False

    if artifact.get("decision") not in VALID_DECISIONS:
        return False

    if not isinstance(artifact.get("features"), dict):
        return False

    if artifact.get("reward") is not None and not isinstance(artifact.get("reward"), (int, float)):
        return False

    if artifact.get("confidence") is not None:
        confidence = artifact.get("confidence")
        if not isinstance(confidence, (int, float)):
            return False
        if not (0.0 <= float(confidence) <= 1.0):
            return False

    locks = artifact.get("safety_locks", {})
    return (
        locks.get("database_writes_allowed") is False
        and locks.get("strategy_db_write_allowed") is False
        and locks.get("promotion_enabled") is False
        and locks.get("broker_execution_enabled") is False
        and locks.get("live_execution_enabled") is False
        and locks.get("source_csv_modification_allowed") is False
    )


def build_empty_learning_artifact_contract() -> dict[str, Any]:
    return build_learning_artifact_contract(
        run_id="EMPTY",
        symbol="EMPTY",
        date="1970-01-01",
        cycle=0,
        features={},
        decision="HOLD",
        reward=None,
        confidence=None,
        source={"empty_contract": True},
    )
'''

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)

TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "contract_keys_present": "LEARNING_ARTIFACT_CONTRACT_KEYS" in text,
    "builder_present": "def build_learning_artifact_contract" in text,
    "validator_present": "def validate_learning_artifact_contract" in text,
    "empty_builder_present": "def build_empty_learning_artifact_contract" in text,
    "valid_decisions_present": "VALID_DECISIONS" in text,
    "safety_locks_present": "SAFETY_LOCKS" in text,
    "db_write_blocked": '"database_writes_allowed": False' in text,
    "broker_live_blocked": (
        '"broker_execution_enabled": False' in text
        and '"live_execution_enabled": False' in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "learning_artifact_contract_created": True,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "121E_LEARNING_FEATURE_EXTRACTOR_STUB",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        f"target_file: {TARGET}",
        "",
        "Learning artifact contract stub created.",
        "No DB writes. No promotion. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
