#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "strategy_knowledge_certification/124C_strategy_knowledge_certification_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/indicator_knowledge_graph.py"

OUT_DIR = ARCH / "indicator_knowledge_graph_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "125A_indicator_knowledge_graph_stub_latest.json"
OUT_TXT = OUT_DIR / "125A_indicator_knowledge_graph_stub_latest.txt"

PHASE = "125A_INDICATOR_KNOWLEDGE_GRAPH_STUB"

SOURCE_TEXT = '''"""Indicator knowledge graph.

Generated by 125A_INDICATOR_KNOWLEDGE_GRAPH_STUB.

Links indicators to strategy families, regimes, symbols, and evidence.
No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
}

GRAPH_KEYS = {
    "graph_id",
    "nodes",
    "edges",
    "source_knowledge_objects",
    "safety_locks",
    "created_at",
}

def graph_status() -> dict[str, Any]:
    return {
        "indicator_knowledge_graph_enabled": True,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }

def _node(node_type: str, name: str, metadata: dict[str, Any] | None = None) -> dict[str, Any]:
    return {
        "id": f"{node_type}:{name}".upper().replace(" ", "_"),
        "type": node_type,
        "name": name,
        "metadata": metadata or {},
    }

def _edge(source: str, target: str, relationship: str, evidence: dict[str, Any] | None = None) -> dict[str, Any]:
    return {
        "source": source,
        "target": target,
        "relationship": relationship,
        "evidence": evidence or {},
    }

def build_indicator_knowledge_graph(
    knowledge_objects: list[dict[str, Any]],
) -> dict[str, Any]:
    nodes_by_id: dict[str, dict[str, Any]] = {}
    edges: list[dict[str, Any]] = []
    source_refs: list[dict[str, Any]] = []

    for obj in knowledge_objects:
        knowledge_id = obj.get("knowledge_id")
        strategy_name = obj.get("strategy_name") or "UNKNOWN_STRATEGY"
        strategy_family = obj.get("strategy_family") or "UNCLASSIFIED"
        indicators = obj.get("indicators") or []
        symbols = obj.get("symbols") or []
        regimes = obj.get("regimes") or []

        strategy_node = _node("strategy", strategy_name, {"family": strategy_family})
        nodes_by_id[strategy_node["id"]] = strategy_node

        family_node = _node("strategy_family", strategy_family)
        nodes_by_id[family_node["id"]] = family_node

        edges.append(_edge(strategy_node["id"], family_node["id"], "BELONGS_TO_FAMILY", {"knowledge_id": knowledge_id}))

        for indicator in indicators:
            indicator_node = _node("indicator", str(indicator))
            nodes_by_id[indicator_node["id"]] = indicator_node
            edges.append(_edge(strategy_node["id"], indicator_node["id"], "USES_INDICATOR", {"knowledge_id": knowledge_id}))

        for symbol in symbols:
            symbol_node = _node("symbol", str(symbol))
            nodes_by_id[symbol_node["id"]] = symbol_node
            edges.append(_edge(strategy_node["id"], symbol_node["id"], "OBSERVED_ON_SYMBOL", {"knowledge_id": knowledge_id}))

        for regime in regimes:
            regime_node = _node("regime", str(regime))
            nodes_by_id[regime_node["id"]] = regime_node
            edges.append(_edge(strategy_node["id"], regime_node["id"], "ASSOCIATED_WITH_REGIME", {"knowledge_id": knowledge_id}))

        source_refs.append({
            "knowledge_id": knowledge_id,
            "strategy_name": strategy_name,
            "confidence": obj.get("confidence"),
        })

    return {
        "graph_id": "INDICATOR_KNOWLEDGE_GRAPH_V1",
        "nodes": list(nodes_by_id.values()),
        "edges": edges,
        "source_knowledge_objects": source_refs,
        "safety_locks": dict(SAFETY_LOCKS),
        "created_at": datetime.now(UTC).isoformat(),
    }

def validate_indicator_knowledge_graph(graph: dict[str, Any]) -> bool:
    if set(graph.keys()) != GRAPH_KEYS:
        return False

    if not isinstance(graph.get("nodes"), list):
        return False

    if not isinstance(graph.get("edges"), list):
        return False

    for node in graph.get("nodes", []):
        if not {"id", "type", "name", "metadata"}.issubset(set(node.keys())):
            return False

    for edge in graph.get("edges", []):
        if not {"source", "target", "relationship", "evidence"}.issubset(set(edge.keys())):
            return False

    locks = graph.get("safety_locks", {})
    return (
        locks.get("database_writes_allowed") is False
        and locks.get("strategy_db_write_allowed") is False
        and locks.get("promotion_enabled") is False
        and locks.get("broker_execution_enabled") is False
        and locks.get("live_execution_enabled") is False
    )
'''

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "status_present": "def graph_status" in text,
    "builder_present": "def build_indicator_knowledge_graph" in text,
    "validator_present": "def validate_indicator_knowledge_graph" in text,
    "nodes_edges_present": "nodes" in text and "edges" in text,
    "db_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "indicator_knowledge_graph_created": True,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "125B_INDICATOR_KNOWLEDGE_GRAPH_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        f"target_file: {TARGET}",
        "",
        "Indicator knowledge graph stub created.",
        "No DB writes. No promotion. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
