#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "learning_artifact_contract_stub/121D_learning_artifact_contract_stub_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_feature_extractor.py"

OUT_DIR = ARCH / "learning_feature_extractor_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "121E_learning_feature_extractor_stub_latest.json"
OUT_TXT = OUT_DIR / "121E_learning_feature_extractor_stub_latest.txt"

PHASE = "121E_LEARNING_FEATURE_EXTRACTOR_STUB"

SOURCE_TEXT = '''"""Learning feature extractor.

Generated by 121E_LEARNING_FEATURE_EXTRACTOR_STUB.

Creates read-only feature vectors from replay OHLCV rows.
No source CSV mutation.
No DB writes.
No broker/live execution.
"""

from __future__ import annotations

from typing import Any
import math

FEATURE_EXTRACTOR_ENABLED = True
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False
SOURCE_CSV_MODIFICATION_ALLOWED = False

FEATURE_KEYS = {
    "open",
    "high",
    "low",
    "close",
    "volume",
    "intraday_return",
    "range_pct",
    "close_position_in_range",
    "previous_close",
    "daily_return",
    "valid_numeric_row",
}


def _num(value: Any) -> float | None:
    try:
        number = float(value)
        if math.isfinite(number):
            return number
        return None
    except Exception:
        return None


def extractor_status() -> dict[str, Any]:
    return {
        "feature_extractor_enabled": FEATURE_EXTRACTOR_ENABLED,
        "feature_keys": sorted(FEATURE_KEYS),
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
        "source_csv_modification_allowed": SOURCE_CSV_MODIFICATION_ALLOWED,
    }


def extract_learning_features(row: dict[str, Any], previous_close: float | None = None) -> dict[str, Any]:
    open_price = _num(row.get("open"))
    high = _num(row.get("high"))
    low = _num(row.get("low"))
    close = _num(row.get("close"))
    volume = _num(row.get("volume"))

    valid = all(v is not None for v in [open_price, high, low, close, volume])

    intraday_return = None
    range_pct = None
    close_position_in_range = None
    daily_return = None

    if valid:
        if open_price and open_price > 0:
            intraday_return = (close / open_price) - 1.0

        if low is not None and high is not None and close is not None:
            if high > low:
                range_pct = (high - low) / close if close and close > 0 else None
                close_position_in_range = (close - low) / (high - low)

        if previous_close is not None and previous_close > 0:
            daily_return = (close / previous_close) - 1.0

    return {
        "open": open_price,
        "high": high,
        "low": low,
        "close": close,
        "volume": volume,
        "intraday_return": intraday_return,
        "range_pct": range_pct,
        "close_position_in_range": close_position_in_range,
        "previous_close": previous_close,
        "daily_return": daily_return,
        "valid_numeric_row": valid,
    }


def validate_learning_features(features: dict[str, Any]) -> bool:
    if set(features.keys()) != FEATURE_KEYS:
        return False

    if features.get("valid_numeric_row") is not True:
        return False

    for key, value in features.items():
        if key == "valid_numeric_row":
            continue
        if value is not None:
            try:
                if not math.isfinite(float(value)):
                    return False
            except Exception:
                return False

    return (
        DATABASE_WRITES_ALLOWED is False
        and STRATEGY_DB_WRITE_ALLOWED is False
        and PROMOTION_ENABLED is False
        and BROKER_EXECUTION_ENABLED is False
        and LIVE_EXECUTION_ENABLED is False
        and SOURCE_CSV_MODIFICATION_ALLOWED is False
    )
'''

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "feature_keys_present": "FEATURE_KEYS" in text,
    "extractor_present": "def extract_learning_features" in text,
    "validator_present": "def validate_learning_features" in text,
    "status_present": "def extractor_status" in text,
    "db_write_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "source_csv_modification_blocked": "SOURCE_CSV_MODIFICATION_ALLOWED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "learning_feature_extractor_created": True,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
        "source_csv_modification_allowed": False,
    },
    "recommended_next_phase": "121F_LEARNING_REWARD_SCORER_STUB",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        f"target_file: {TARGET}",
        "",
        "Learning feature extractor stub created.",
        "No DB writes. No source CSV mutation. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
