#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "indicator_knowledge_graph_certification/125B_indicator_knowledge_graph_certification_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/symbol_intelligence_profile.py"

OUT_DIR = ARCH / "symbol_intelligence_profile_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "126A_symbol_intelligence_profile_stub_latest.json"
OUT_TXT = OUT_DIR / "126A_symbol_intelligence_profile_stub_latest.txt"

PHASE = "126A_SYMBOL_INTELLIGENCE_PROFILE_STUB"

SOURCE_TEXT = '''"""Symbol Intelligence Profile.

Generated by 126A_SYMBOL_INTELLIGENCE_PROFILE_STUB.

Creates read-only symbol intelligence profiles from learning artifacts,
strategy knowledge, and indicator knowledge graphs.

No database writes.
No strategy promotion.
No broker/live execution.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Any

DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

SAFETY_LOCKS = {
    "database_writes_allowed": False,
    "strategy_db_write_allowed": False,
    "promotion_enabled": False,
    "broker_execution_enabled": False,
    "live_execution_enabled": False,
}

PROFILE_KEYS = {
    "symbol",
    "profile_id",
    "asset_class",
    "strategy_families",
    "strategies",
    "indicators",
    "regimes",
    "average_reward",
    "average_confidence",
    "observations",
    "evidence",
    "safety_locks",
    "created_at",
}

def profile_status() -> dict[str, Any]:
    return {
        "symbol_profile_enabled": True,
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }

def build_symbol_intelligence_profile(
    *,
    symbol: str,
    knowledge_objects: list[dict[str, Any]],
) -> dict[str, Any]:

    strategy_families=set()
    strategies=set()
    indicators=set()
    regimes=set()
    evidence=[]
    rewards=[]
    confidence=[]

    for obj in knowledge_objects:

        if symbol not in (obj.get("symbols") or []):
            continue

        strategy_families.add(obj.get("strategy_family","UNKNOWN"))
        strategies.add(obj.get("strategy_name","UNKNOWN"))

        indicators.update(obj.get("indicators") or [])
        regimes.update(obj.get("regimes") or [])

        for e in obj.get("evidence",[]):
            evidence.append(e)

        for s in obj.get("source_artifacts",[]):
            r=s.get("reward")
            if isinstance(r,(int,float)):
                rewards.append(float(r))

        c=obj.get("confidence")
        if isinstance(c,(int,float)):
            confidence.append(float(c))

    avg_reward=(
        sum(rewards)/len(rewards)
        if rewards else None
    )

    avg_conf=(
        sum(confidence)/len(confidence)
        if confidence else 0.0
    )

    return {

        "symbol":symbol,
        "profile_id":f"SYMBOL_PROFILE:{symbol}",
        "asset_class":"UNKNOWN",

        "strategy_families":sorted(strategy_families),
        "strategies":sorted(strategies),
        "indicators":sorted(indicators),
        "regimes":sorted(regimes),

        "average_reward":avg_reward,
        "average_confidence":avg_conf,

        "observations":len(evidence),

        "evidence":evidence,

        "safety_locks":dict(SAFETY_LOCKS),

        "created_at":datetime.now(UTC).isoformat(),
    }

def validate_symbol_intelligence_profile(profile:dict[str,Any])->bool:

    if set(profile.keys())!=PROFILE_KEYS:
        return False

    if not profile.get("symbol"):
        return False

    if not isinstance(profile.get("strategies"),list):
        return False

    if not isinstance(profile.get("indicators"),list):
        return False

    if not isinstance(profile.get("regimes"),list):
        return False

    locks=profile.get("safety_locks",{})

    return (

        locks.get("database_writes_allowed") is False
        and
        locks.get("strategy_db_write_allowed") is False
        and
        locks.get("promotion_enabled") is False
        and
        locks.get("broker_execution_enabled") is False
        and
        locks.get("live_execution_enabled") is False
    )
'''

def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source=read_json(SOURCE)

TARGET.write_text(SOURCE_TEXT,encoding="utf-8")

compile_ok=False
compile_error=None

try:
    py_compile.compile(str(TARGET),doraise=True)
    compile_ok=True
except Exception as exc:
    compile_error={
        "type":type(exc).__name__,
        "message":str(exc),
    }

text=TARGET.read_text(encoding="utf-8")

checks={

    "source_exists":SOURCE.exists(),
    "source_certified":source.get("certified") is True,

    "target_written":TARGET.exists(),

    "compile_ok":compile_ok,

    "status_present":"def profile_status" in text,
    "builder_present":"def build_symbol_intelligence_profile" in text,
    "validator_present":"def validate_symbol_intelligence_profile" in text,

    "profile_keys_present":"PROFILE_KEYS" in text,

    "db_blocked":"DATABASE_WRITES_ALLOWED = False" in text,

    "promotion_blocked":"PROMOTION_ENABLED = False" in text,

    "broker_live_blocked":(
        "BROKER_EXECUTION_ENABLED = False" in text
        and
        "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result={

    "phase":PHASE,
    "created_at":datetime.now(UTC).isoformat(),

    "target_file":str(TARGET),

    "compile_error":compile_error,

    "checks":checks,

    "policy":{

        "symbol_profile_created":True,

        "database_writes_allowed":False,
        "strategy_db_write_allowed":False,
        "promotion_enabled":False,
        "broker_execution_enabled":False,
        "live_execution_enabled":False,
    },

    "recommended_next_phase":
        "126B_SYMBOL_INTELLIGENCE_PROFILE_CERTIFICATION",

    "certified":
        all(checks.values()),
}

OUT_JSON.write_text(
    json.dumps(result,indent=2),
    encoding="utf-8",
)

OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "",
        "Creates read-only symbol intelligence profiles.",
        "Aggregates:",
        "- strategies",
        "- strategy families",
        "- indicators",
        "- regimes",
        "- evidence",
        "- average reward",
        "- average confidence",
        "",
        "Database Writes: False",
        "Promotion: False",
        "Broker: False",
        "Live: False",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({

    "phase":PHASE,
    "certified":result["certified"],
    "compile_ok":compile_ok,
    "recommended_next_phase":
        result["recommended_next_phase"],
    "out_json":str(OUT_JSON),
    "out_txt":str(OUT_TXT),

},indent=2))
