#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "learning_reward_scorer_stub/121F_learning_reward_scorer_stub_latest.json"

CONTRACT = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_artifact_contract.py"
FEATURES = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_feature_extractor.py"
REWARDS = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_reward_scorer.py"

TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/learning_artifact_pipeline.py"

OUT_DIR = ARCH / "learning_artifact_pipeline_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "123B_learning_artifact_pipeline_stub_latest.json"
OUT_TXT  = OUT_DIR / "123B_learning_artifact_pipeline_stub_latest.txt"

PHASE = "123B_LEARNING_ARTIFACT_PIPELINE_STUB"

SOURCE_TEXT = '''"""
Learning Artifact Pipeline

Generated by 123B_LEARNING_ARTIFACT_PIPELINE_STUB

Read-only pipeline:

Replay Row
    ↓
Feature Extraction
    ↓
Decision
    ↓
Reward
    ↓
Learning Artifact

NO DATABASE WRITES
NO STRATEGY PROMOTION
NO BROKER
NO LIVE EXECUTION
"""

from __future__ import annotations

from typing import Any

from backend.app.stacks.strategy_candidate_sandbox.learning_feature_extractor import (
    extract_learning_features,
)

from backend.app.stacks.strategy_candidate_sandbox.learning_reward_scorer import (
    score_decision_reward,
)

from backend.app.stacks.strategy_candidate_sandbox.learning_artifact_contract import (
    build_learning_artifact_contract,
)

PIPELINE_ENABLED=True

DATABASE_WRITES_ALLOWED=False
STRATEGY_DB_WRITE_ALLOWED=False
PROMOTION_ENABLED=False
BROKER_EXECUTION_ENABLED=False
LIVE_EXECUTION_ENABLED=False


def pipeline_status()->dict:

    return {

        "pipeline_enabled":PIPELINE_ENABLED,
        "database_writes_allowed":DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed":STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled":PROMOTION_ENABLED,
        "broker_execution_enabled":BROKER_EXECUTION_ENABLED,
        "live_execution_enabled":LIVE_EXECUTION_ENABLED,
    }


def build_learning_artifact(

    *,
    run_id:str,
    symbol:str,
    row:dict[str,Any],
    previous_close:float|None,
    next_close:float|None,
    decision:str,
    cycle:int,

)->dict:

    features=extract_learning_features(
        row,
        previous_close,
    )

    reward=score_decision_reward(
        decision,
        row.get("close"),
        next_close,
    )

    artifact=build_learning_artifact_contract(

        run_id=run_id,
        symbol=symbol,
        date=str(row.get("date")),
        cycle=cycle,
        features=features,
        decision=decision,
        reward=reward["reward"],
        confidence=reward["confidence"],
        source={
            "reward":reward,
            "pipeline":"learning_artifact_pipeline",
        },
    )

    return artifact
'''

def read_json(path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}

source = read_json(SOURCE)

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {
        "type": type(exc).__name__,
        "message": str(exc),
    }
else:
    compile_error = None

text = TARGET.read_text()

checks = {

    "source_exists": SOURCE.exists(),

    "source_certified":
        source.get("certified") is True,

    "contract_exists":
        CONTRACT.exists(),

    "feature_extractor_exists":
        FEATURES.exists(),

    "reward_scorer_exists":
        REWARDS.exists(),

    "target_exists":
        TARGET.exists(),

    "compile_ok":
        compile_ok,

    "feature_connected":
        "extract_learning_features" in text,

    "reward_connected":
        "score_decision_reward" in text,

    "artifact_connected":
        "build_learning_artifact_contract" in text,

    "pipeline_builder_present":
        "build_learning_artifact" in text,

    "db_blocked":
        "DATABASE_WRITES_ALLOWED=False" in text,

    "broker_blocked":
        "BROKER_EXECUTION_ENABLED=False" in text,

    "live_blocked":
        "LIVE_EXECUTION_ENABLED=False" in text,
}

result = {

    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,

    "policy": {

        "pipeline_created": True,

        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },

    "recommended_next_phase":
        "123C_LEARNING_ARTIFACT_PIPELINE_CERTIFICATION",

    "certified":
        all(checks.values()),
}

OUT_JSON.write_text(
    json.dumps(result, indent=2),
    encoding="utf-8",
)

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        "",
        "Pipeline:",
        "Replay Row",
        " -> Features",
        " -> Reward",
        " -> Learning Artifact",
        "",
        "Database Writes: False",
        "Promotion: False",
        "Broker: False",
        "Live: False",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({

    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase":
        result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),

}, indent=2))
