#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "candidate_quarantine_trash_path_rollup" / "81C_candidate_quarantine_trash_path_rollup_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/training_read_only_learner.py"

OUT_DIR = ARCH / "training_read_only_learner"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "82A_training_read_only_learner_stub_latest.json"
OUT_TXT = OUT_DIR / "82A_training_read_only_learner_stub_latest.txt"

PHASE = "82A_TRAINING_READ_ONLY_LEARNER_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Training read-only learner stub.

Generated by 82A_TRAINING_READ_ONLY_LEARNER_STUB.

Learner is read-only and disabled.
No training execution, no mutation, no queue writes,
no strategy DB writes, no promotion, no broker execution, no live trading.
"""

TRAINING_ENABLED = False
READ_ONLY_LEARNER_ENABLED = False
LEARNER_WRITE_ENABLED = False
MUTATION_ALLOWED = False
QUEUE_WRITE_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def learner_status() -> dict:
    return {
        "training_enabled": TRAINING_ENABLED,
        "read_only_learner_enabled": READ_ONLY_LEARNER_ENABLED,
        "learner_write_enabled": LEARNER_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def preview_learning_input(report_id: str, candidate_id: str) -> dict:
    return {
        "mode": "PREVIEW_ONLY",
        "report_id": report_id,
        "candidate_id": candidate_id,
        "training_allowed_now": TRAINING_ENABLED,
        "mutation_allowed_now": MUTATION_ALLOWED,
        "write_allowed_now": LEARNER_WRITE_ENABLED,
        "status": learner_status(),
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_status": "def learner_status" in text,
    "contains_preview": "def preview_learning_input" in text,
    "training_disabled": "TRAINING_ENABLED = False" in text,
    "read_only_learner_disabled": "READ_ONLY_LEARNER_ENABLED = False" in text,
    "learner_write_disabled": "LEARNER_WRITE_ENABLED = False" in text,
    "mutation_blocked": "MUTATION_ALLOWED = False" in text,
    "queue_write_blocked": "QUEUE_WRITE_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "TRAINING_READ_ONLY_LEARNER_STUB",
    "source_quarantine_rollup": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "training_read_only_learner_stub_created": True,
        "training_enabled": False,
        "read_only_learner_enabled": False,
        "learner_write_enabled": False,
        "mutation_allowed": False,
        "queue_write_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "82B_TRAINING_READ_ONLY_LEARNER_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Training read-only learner stub created.",
        "Training/write/mutation/queue/db/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
