#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "learning_feature_extractor_stub/121E_learning_feature_extractor_stub_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/learning_reward_scorer.py"

OUT_DIR = ARCH / "learning_reward_scorer_stub"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "121F_learning_reward_scorer_stub_latest.json"
OUT_TXT = OUT_DIR / "121F_learning_reward_scorer_stub_latest.txt"

PHASE = "121F_LEARNING_REWARD_SCORER_STUB"

SOURCE_TEXT = '''"""Learning reward scorer.

Generated by 121F_LEARNING_REWARD_SCORER_STUB.

Scores replay decisions using next-bar movement only.
No DB writes.
No promotion.
No broker/live execution.
"""

from __future__ import annotations

from typing import Any
import math

REWARD_SCORER_ENABLED = True
DATABASE_WRITES_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False

VALID_DECISIONS = {"BUY", "SELL", "HOLD"}


def _num(value: Any) -> float | None:
    try:
        number = float(value)
        if math.isfinite(number):
            return number
        return None
    except Exception:
        return None


def scorer_status() -> dict[str, Any]:
    return {
        "reward_scorer_enabled": REWARD_SCORER_ENABLED,
        "valid_decisions": sorted(VALID_DECISIONS),
        "database_writes_allowed": DATABASE_WRITES_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def score_decision_reward(
    decision: str,
    current_close: Any,
    next_close: Any,
) -> dict[str, Any]:
    decision = str(decision).upper()
    cur = _num(current_close)
    nxt = _num(next_close)

    if decision not in VALID_DECISIONS or cur is None or nxt is None or cur <= 0:
        return {
            "reward": 0.0,
            "confidence": 0.0,
            "next_return": None,
            "valid_reward": False,
            "reason": "invalid reward input",
        }

    next_return = (nxt / cur) - 1.0

    if decision == "BUY":
        reward = next_return
    elif decision == "SELL":
        reward = -next_return
    else:
        reward = -abs(next_return) * 0.1

    confidence = min(1.0, abs(next_return) * 50.0)

    return {
        "reward": float(reward),
        "confidence": float(confidence),
        "next_return": float(next_return),
        "valid_reward": True,
        "reason": "next-bar reward scored",
    }


def validate_reward_score(score: dict[str, Any]) -> bool:
    required = {"reward", "confidence", "next_return", "valid_reward", "reason"}
    if set(score.keys()) != required:
        return False

    if score.get("valid_reward") is not True:
        return False

    reward = _num(score.get("reward"))
    confidence = _num(score.get("confidence"))

    if reward is None or confidence is None:
        return False

    if not (0.0 <= confidence <= 1.0):
        return False

    return (
        DATABASE_WRITES_ALLOWED is False
        and STRATEGY_DB_WRITE_ALLOWED is False
        and PROMOTION_ENABLED is False
        and BROKER_EXECUTION_ENABLED is False
        and LIVE_EXECUTION_ENABLED is False
    )
'''

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

source = read_json(SOURCE)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "compile_ok": compile_ok,
    "scorer_present": "def score_decision_reward" in text,
    "validator_present": "def validate_reward_score" in text,
    "status_present": "def scorer_status" in text,
    "valid_decisions_present": "VALID_DECISIONS" in text,
    "db_write_blocked": "DATABASE_WRITES_ALLOWED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "checks": checks,
    "policy": {
        "learning_reward_scorer_created": True,
        "database_writes_allowed": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "recommended_next_phase": "121G_LEARNING_ARTIFACT_PIPELINE_STUB",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")
OUT_TXT.write_text(
    "\\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"compile_ok: {compile_ok}",
        f"target_file: {TARGET}",
        "",
        "Learning reward scorer stub created.",
        "No DB writes. No promotion. No broker/live.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
