#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "stress_test_report_rollup" / "78C_stress_test_report_rollup_certification_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L1_security_auth_safety/manual_activation_gate.py"

OUT_DIR = ARCH / "manual_activation_gate"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "79A_manual_activation_gate_stub_latest.json"
OUT_TXT = OUT_DIR / "79A_manual_activation_gate_stub_latest.txt"

PHASE = "79A_MANUAL_ACTIVATION_GATE_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Manual activation gate.

Generated by 79A_MANUAL_ACTIVATION_GATE_STUB.

Manual activation is explicitly disabled.
This gate prevents automatic promotion, strategy DB writes,
training activation, broker execution, and live trading.
"""

MANUAL_ACTIVATION_ENABLED = False
AUTOMATIC_ACTIVATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def manual_activation_gate_status() -> dict:
    return {
        "manual_activation_enabled": MANUAL_ACTIVATION_ENABLED,
        "automatic_activation_allowed": AUTOMATIC_ACTIVATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_gate_status": "def manual_activation_gate_status" in text,
    "manual_activation_disabled": "MANUAL_ACTIVATION_ENABLED = False" in text,
    "automatic_activation_blocked": "AUTOMATIC_ACTIVATION_ALLOWED = False" in text,
    "training_blocked": "TRAINING_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "MANUAL_ACTIVATION_GATE_STUB",
    "source_stress_rollup": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "manual_activation_gate_stub_created": True,
        "manual_activation_enabled": False,
        "automatic_activation_allowed": False,
        "training_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "79B_MANUAL_ACTIVATION_GATE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Manual activation remains blocked.",
        "Automatic activation/training/db/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
