#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, UTC
import json
import py_compile

ROOT = Path(".").resolve()
ARCH = ROOT / "runtime" / "replay_runtime_architecture"

SOURCE = ARCH / "manual_activation_gate_rollup" / "79C_manual_activation_gate_rollup_latest.json"
TARGET = ROOT / "backend/app/stacks/strategy_candidate_sandbox/L3_service_facade/near_miss_refactor_queue.py"

OUT_DIR = ARCH / "near_miss_refactor_queue"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_JSON = OUT_DIR / "80A_near_miss_refactor_queue_stub_latest.json"
OUT_TXT = OUT_DIR / "80A_near_miss_refactor_queue_stub_latest.txt"

PHASE = "80A_NEAR_MISS_REFACTOR_QUEUE_STUB"


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


source = read_json(SOURCE)

SOURCE_TEXT = '''"""Near-miss refactor queue stub.

Generated by 80A_NEAR_MISS_REFACTOR_QUEUE_STUB.

Queue is contract-only.
No mutation, no training, no strategy DB write,
no promotion, no broker execution, no live trading.
"""

MAX_REFACTOR_ATTEMPTS = 3
QUEUE_WRITE_ENABLED = False
MUTATION_ALLOWED = False
TRAINING_ENABLED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def near_miss_queue_status() -> dict:
    return {
        "max_refactor_attempts": MAX_REFACTOR_ATTEMPTS,
        "queue_write_enabled": QUEUE_WRITE_ENABLED,
        "mutation_allowed": MUTATION_ALLOWED,
        "training_enabled": TRAINING_ENABLED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }


def validate_attempt_count(attempt_count: int) -> dict:
    return {
        "attempt_count": attempt_count,
        "max_refactor_attempts": MAX_REFACTOR_ATTEMPTS,
        "allowed": 0 <= attempt_count <= MAX_REFACTOR_ATTEMPTS,
    }
'''

TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(SOURCE_TEXT, encoding="utf-8")

compile_ok = False
compile_error = None

try:
    py_compile.compile(str(TARGET), doraise=True)
    compile_ok = True
except Exception as exc:
    compile_error = {"type": type(exc).__name__, "message": str(exc)}

text = TARGET.read_text(encoding="utf-8")

checks = {
    "source_exists": SOURCE.exists(),
    "source_certified": source.get("certified") is True,
    "target_written": TARGET.exists(),
    "target_compile_ok": compile_ok,
    "contains_status": "def near_miss_queue_status" in text,
    "contains_attempt_validator": "def validate_attempt_count" in text,
    "attempts_capped_at_3": "MAX_REFACTOR_ATTEMPTS = 3" in text,
    "queue_write_disabled": "QUEUE_WRITE_ENABLED = False" in text,
    "mutation_blocked": "MUTATION_ALLOWED = False" in text,
    "training_blocked": "TRAINING_ENABLED = False" in text,
    "strategy_db_write_blocked": "STRATEGY_DB_WRITE_ALLOWED = False" in text,
    "promotion_blocked": "PROMOTION_ENABLED = False" in text,
    "broker_live_blocked": (
        "BROKER_EXECUTION_ENABLED = False" in text
        and "LIVE_EXECUTION_ENABLED = False" in text
    ),
}

result = {
    "phase": PHASE,
    "created_at": datetime.now(UTC).isoformat(),
    "mode": "NEAR_MISS_REFACTOR_QUEUE_STUB",
    "source_manual_activation_rollup": str(SOURCE),
    "target_file": str(TARGET),
    "compile_error": compile_error,
    "policy": {
        "near_miss_refactor_queue_stub_created": True,
        "max_refactor_attempts": 3,
        "queue_write_enabled": False,
        "mutation_allowed": False,
        "training_enabled": False,
        "strategy_db_write_allowed": False,
        "promotion_enabled": False,
        "broker_execution_enabled": False,
        "live_execution_enabled": False,
    },
    "checks": checks,
    "recommended_next_phase": "80B_NEAR_MISS_REFACTOR_QUEUE_CERTIFICATION",
    "certified": all(checks.values()),
}

OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

OUT_TXT.write_text(
    "\n".join([
        PHASE,
        "",
        f"certified: {result['certified']}",
        f"target_file: {TARGET}",
        f"compile_ok: {compile_ok}",
        "",
        "Near-miss queue stub created.",
        "Queue write/mutation/training/db/promotion/broker/live remain blocked.",
        "",
        "Next:",
        result["recommended_next_phase"],
    ]),
    encoding="utf-8",
)

print(json.dumps({
    "phase": PHASE,
    "certified": result["certified"],
    "target_file": str(TARGET),
    "compile_ok": compile_ok,
    "recommended_next_phase": result["recommended_next_phase"],
    "out_json": str(OUT_JSON),
    "out_txt": str(OUT_TXT),
}, indent=2))
