"""Read-only replay contract stub.

Generated by 67A_REPLAY_CONTRACT_SOURCE_CREATION.

This file defines contract shape only.
It must not execute replay, mutate runtime, write strategy DB,
promote candidates, place broker orders, or enable live trading.
"""

REPLAY_RUNTIME_ENABLED = False
HISTORICAL_REPLAY_ALLOWED = False
STRATEGY_EXECUTION_ALLOWED = False
STRATEGY_DB_WRITE_ALLOWED = False
PROMOTION_ENABLED = False
BROKER_EXECUTION_ENABLED = False
LIVE_EXECUTION_ENABLED = False


def contract_status() -> dict:
    return {
        "replay_runtime_enabled": REPLAY_RUNTIME_ENABLED,
        "historical_replay_allowed": HISTORICAL_REPLAY_ALLOWED,
        "strategy_execution_allowed": STRATEGY_EXECUTION_ALLOWED,
        "strategy_db_write_allowed": STRATEGY_DB_WRITE_ALLOWED,
        "promotion_enabled": PROMOTION_ENABLED,
        "broker_execution_enabled": BROKER_EXECUTION_ENABLED,
        "live_execution_enabled": LIVE_EXECUTION_ENABLED,
    }
